:- module(gl_defs,[gl_opts/2]).
:- use_module(library(arithmetic)).
% Definitions and Keys from gl.h

%typedef double		GLclampd;	/* double precision float in [0,1] */
%typedef double		GLdouble;	/* double precision float */
%typedef float		GLclampf;	/* single precision float in [0,1] */
%typedef float		GLfloat;	/* single precision float */
%typedef int		GLint;		/* 4-byte signed */
%typedef int		GLsizei;	/* 4-byte signed */
%typedef short		GLshort;	/* 2-byte signed */
%typedef signed char	GLbyte;		/* 1-byte signed */
%typedef unsigned char	GLboolean;
%typedef unsigned char	GLubyte;	/* 1-byte unsigned */
%typedef unsigned int	GLbitfield;
%typedef unsigned int	GLenum;
%typedef unsigned int	GLuint;		/* 4-byte unsigned */
%typedef unsigned short	GLushort;	/* 2-byte unsigned */
%typedef void		GLvoid;

:-arithmetic_function(gl_GL_2_BYTES/0).
:-arithmetic_function(gl_GL_2D/0).
:-arithmetic_function(gl_GL_3_BYTES/0).
:-arithmetic_function(gl_GL_3D/0).
:-arithmetic_function(gl_GL_3D_COLOR/0).
:-arithmetic_function(gl_GL_3D_COLOR_TEXTURE/0).
:-arithmetic_function(gl_GL_4_BYTES/0).
:-arithmetic_function(gl_GL_4D_COLOR_TEXTURE/0).
:-arithmetic_function(gl_GL_ABGR_EXT/0).
:-arithmetic_function(gl_GL_ACCUM/0).
:-arithmetic_function(gl_GL_ACCUM_ALPHA_BITS/0).
:-arithmetic_function(gl_GL_ACCUM_BLUE_BITS/0).
:-arithmetic_function(gl_GL_ACCUM_BUFFER_BIT/0).
:-arithmetic_function(gl_GL_ACCUM_CLEAR_VALUE/0).
:-arithmetic_function(gl_GL_ACCUM_GREEN_BITS/0).
:-arithmetic_function(gl_GL_ACCUM_RED_BITS/0).
:-arithmetic_function(gl_GL_ACTIVE_TEXTURE_ARB/0).
:-arithmetic_function(gl_GL_ADD/0).
:-arithmetic_function(gl_GL_ALIASED_LINE_WIDTH_RANGE/0).
:-arithmetic_function(gl_GL_ALIASED_POINT_SIZE_RANGE/0).
:-arithmetic_function(gl_GL_ALL_ATTRIB_BITS/0).
:-arithmetic_function(gl_GL_ALL_CLIENT_ATTRIB_BITS/0).
:-arithmetic_function(gl_GL_ALPHA/0).
:-arithmetic_function(gl_GL_ALPHA12/0).
:-arithmetic_function(gl_GL_ALPHA16/0).
:-arithmetic_function(gl_GL_ALPHA4/0).
:-arithmetic_function(gl_GL_ALPHA8/0).
:-arithmetic_function(gl_GL_ALPHA_BIAS/0).
:-arithmetic_function(gl_GL_ALPHA_BITS/0).
:-arithmetic_function(gl_GL_ALPHA_SCALE/0).
:-arithmetic_function(gl_GL_ALPHA_TEST/0).
:-arithmetic_function(gl_GL_ALPHA_TEST_FUNC/0).
:-arithmetic_function(gl_GL_ALPHA_TEST_REF/0).
:-arithmetic_function(gl_GL_ALWAYS/0).
:-arithmetic_function(gl_GL_AMBIENT/0).
:-arithmetic_function(gl_GL_AMBIENT_AND_DIFFUSE/0).
:-arithmetic_function(gl_GL_AND/0).
:-arithmetic_function(gl_GL_AND_INVERTED/0).
:-arithmetic_function(gl_GL_AND_REVERSE/0).
:-arithmetic_function(gl_GL_ARB_multitexture/0).
:-arithmetic_function(gl_GL_ARRAY_ELEMENT_LOCK_COUNT_EXT/0).
:-arithmetic_function(gl_GL_ARRAY_ELEMENT_LOCK_FIRST_EXT/0).
:-arithmetic_function(gl_GL_ATTRIB_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_AUTO_NORMAL/0).
:-arithmetic_function(gl_GL_AUX0/0).
:-arithmetic_function(gl_GL_AUX1/0).
:-arithmetic_function(gl_GL_AUX2/0).
:-arithmetic_function(gl_GL_AUX3/0).
:-arithmetic_function(gl_GL_AUX_BUFFERS/0).
:-arithmetic_function(gl_GL_BACK/0).
:-arithmetic_function(gl_GL_BACK_LEFT/0).
:-arithmetic_function(gl_GL_BACK_RIGHT/0).
:-arithmetic_function(gl_GL_BGR/0).
:-arithmetic_function(gl_GL_BGRA/0).
:-arithmetic_function(gl_GL_BITMAP/0).
:-arithmetic_function(gl_GL_BITMAP_TOKEN/0).
:-arithmetic_function(gl_GL_BLEND/0).
:-arithmetic_function(gl_GL_BLEND_COLOR/0).
:-arithmetic_function(gl_GL_BLEND_COLOR_EXT/0).
:-arithmetic_function(gl_GL_BLEND_DST/0).
:-arithmetic_function(gl_GL_BLEND_EQUATION/0).
:-arithmetic_function(gl_GL_BLEND_EQUATION_EXT/0).
:-arithmetic_function(gl_GL_BLEND_SRC/0).
:-arithmetic_function(gl_GL_BLUE/0).
:-arithmetic_function(gl_GL_BLUE_BIAS/0).
:-arithmetic_function(gl_GL_BLUE_BITS/0).
:-arithmetic_function(gl_GL_BLUE_SCALE/0).
:-arithmetic_function(gl_GL_BYTE/0).
:-arithmetic_function(gl_GL_C3F_V3F/0).
:-arithmetic_function(gl_GL_C4F_N3F_V3F/0).
:-arithmetic_function(gl_GL_C4UB_V2F/0).
:-arithmetic_function(gl_GL_C4UB_V3F/0).
:-arithmetic_function(gl_GL_CCW/0).
:-arithmetic_function(gl_GL_CLAMP/0).
:-arithmetic_function(gl_GL_CLAMP_TO_EDGE/0).
:-arithmetic_function(gl_GL_CLAMP_TO_EDGE_SGIS/0).
:-arithmetic_function(gl_GL_CLEAR/0).
:-arithmetic_function(gl_GL_CLIENT_ACTIVE_TEXTURE_ARB/0).
:-arithmetic_function(gl_GL_CLIENT_ATTRIB_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_CLIENT_PIXEL_STORE_BIT/0).
:-arithmetic_function(gl_GL_CLIENT_VERTEX_ARRAY_BIT/0).
:-arithmetic_function(gl_GL_CLIP_PLANE0/0).
:-arithmetic_function(gl_GL_CLIP_PLANE1/0).
:-arithmetic_function(gl_GL_CLIP_PLANE2/0).
:-arithmetic_function(gl_GL_CLIP_PLANE3/0).
:-arithmetic_function(gl_GL_CLIP_PLANE4/0).
:-arithmetic_function(gl_GL_CLIP_PLANE5/0).
:-arithmetic_function(gl_GL_CLIP_VOLUME_CLIPPING_HINT_EXT/0).
:-arithmetic_function(gl_GL_COEFF/0).
:-arithmetic_function(gl_GL_COLOR/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_TYPE/0).
:-arithmetic_function(gl_GL_COLOR_ARRAY_TYPE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_BUFFER_BIT/0).
:-arithmetic_function(gl_GL_COLOR_CLEAR_VALUE/0).
:-arithmetic_function(gl_GL_COLOR_INDEX/0).
:-arithmetic_function(gl_GL_COLOR_INDEX12_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEX16_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEX1_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEX2_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEX4_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEX8_EXT/0).
:-arithmetic_function(gl_GL_COLOR_INDEXES/0).
:-arithmetic_function(gl_GL_COLOR_LOGIC_OP/0).
:-arithmetic_function(gl_GL_COLOR_MATERIAL/0).
:-arithmetic_function(gl_GL_COLOR_MATERIAL_FACE/0).
:-arithmetic_function(gl_GL_COLOR_MATERIAL_PARAMETER/0).
:-arithmetic_function(gl_GL_COLOR_MATRIX/0).
:-arithmetic_function(gl_GL_COLOR_MATRIX_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_ALPHA_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_ALPHA_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_BIAS/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_BLUE_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_BLUE_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_FORMAT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_FORMAT_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_GREEN_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_GREEN_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_INTENSITY_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_INTENSITY_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_LUMINANCE_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_LUMINANCE_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_RED_SIZE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_RED_SIZE_EXT/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_SCALE/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_WIDTH/0).
:-arithmetic_function(gl_GL_COLOR_TABLE_WIDTH_EXT/0).
:-arithmetic_function(gl_GL_COLOR_WRITEMASK/0).
:-arithmetic_function(gl_GL_COMPILE/0).
:-arithmetic_function(gl_GL_COMPILE_AND_EXECUTE/0).
:-arithmetic_function(gl_GL_CONSTANT_ALPHA/0).
:-arithmetic_function(gl_GL_CONSTANT_ALPHA_EXT/0).
:-arithmetic_function(gl_GL_CONSTANT_ATTENUATION/0).
:-arithmetic_function(gl_GL_CONSTANT_BORDER/0).
:-arithmetic_function(gl_GL_CONSTANT_COLOR/0).
:-arithmetic_function(gl_GL_CONSTANT_COLOR_EXT/0).
:-arithmetic_function(gl_GL_CONVOLUTION_1D/0).
:-arithmetic_function(gl_GL_CONVOLUTION_2D/0).
:-arithmetic_function(gl_GL_CONVOLUTION_BORDER_COLOR/0).
:-arithmetic_function(gl_GL_CONVOLUTION_BORDER_MODE/0).
:-arithmetic_function(gl_GL_CONVOLUTION_FILTER_BIAS/0).
:-arithmetic_function(gl_GL_CONVOLUTION_FILTER_SCALE/0).
:-arithmetic_function(gl_GL_CONVOLUTION_FORMAT/0).
:-arithmetic_function(gl_GL_CONVOLUTION_HEIGHT/0).
:-arithmetic_function(gl_GL_CONVOLUTION_WIDTH/0).
:-arithmetic_function(gl_GL_COPY/0).
:-arithmetic_function(gl_GL_COPY_INVERTED/0).
:-arithmetic_function(gl_GL_COPY_PIXEL_TOKEN/0).
:-arithmetic_function(gl_GL_CULL_FACE/0).
:-arithmetic_function(gl_GL_CULL_FACE_MODE/0).
:-arithmetic_function(gl_GL_CURRENT_BIT/0).
:-arithmetic_function(gl_GL_CURRENT_COLOR/0).
:-arithmetic_function(gl_GL_CURRENT_INDEX/0).
:-arithmetic_function(gl_GL_CURRENT_NORMAL/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_COLOR/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_DISTANCE/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_INDEX/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_POSITION/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_POSITION_VALID/0).
:-arithmetic_function(gl_GL_CURRENT_RASTER_TEXTURE_COORDS/0).
:-arithmetic_function(gl_GL_CURRENT_TEXTURE_COORDS/0).
:-arithmetic_function(gl_GL_CW/0).
:-arithmetic_function(gl_GL_DECAL/0).
:-arithmetic_function(gl_GL_DECR/0).
:-arithmetic_function(gl_GL_DECR_WRAP_EXT/0).
:-arithmetic_function(gl_GL_DEPTH/0).
:-arithmetic_function(gl_GL_DEPTH_BIAS/0).
:-arithmetic_function(gl_GL_DEPTH_BITS/0).
:-arithmetic_function(gl_GL_DEPTH_BUFFER_BIT/0).
:-arithmetic_function(gl_GL_DEPTH_CLEAR_VALUE/0).
:-arithmetic_function(gl_GL_DEPTH_COMPONENT/0).
:-arithmetic_function(gl_GL_DEPTH_FUNC/0).
:-arithmetic_function(gl_GL_DEPTH_RANGE/0).
:-arithmetic_function(gl_GL_DEPTH_SCALE/0).
:-arithmetic_function(gl_GL_DEPTH_TEST/0).
:-arithmetic_function(gl_GL_DEPTH_WRITEMASK/0).
:-arithmetic_function(gl_GL_DIFFUSE/0).
:-arithmetic_function(gl_GL_DISTANCE_ATTENUATION_EXT/0).
:-arithmetic_function(gl_GL_DITHER/0).
:-arithmetic_function(gl_GL_DOMAIN/0).
:-arithmetic_function(gl_GL_DONT_CARE/0).
:-arithmetic_function(gl_GL_DOUBLE/0).
:-arithmetic_function(gl_GL_DOUBLEBUFFER/0).
:-arithmetic_function(gl_GL_DRAW_BUFFER/0).
:-arithmetic_function(gl_GL_DRAW_PIXEL_TOKEN/0).
:-arithmetic_function(gl_GL_DST_ALPHA/0).
:-arithmetic_function(gl_GL_DST_COLOR/0).
:-arithmetic_function(gl_GL_EDGE_FLAG/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_EDGE_FLAG_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_EMISSION/0).
:-arithmetic_function(gl_GL_ENABLE_BIT/0).
:-arithmetic_function(gl_GL_EQUAL/0).
:-arithmetic_function(gl_GL_EQUIV/0).
:-arithmetic_function(gl_GL_EVAL_BIT/0).
:-arithmetic_function(gl_GL_EXP/0).
:-arithmetic_function(gl_GL_EXP2/0).
:-arithmetic_function(gl_GL_EXT_abgr/0).
:-arithmetic_function(gl_GL_EXT_blend_color/0).
:-arithmetic_function(gl_GL_EXT_blend_logic_op/0).
:-arithmetic_function(gl_GL_EXT_blend_minmax/0).
:-arithmetic_function(gl_GL_EXT_blend_subtract/0).
:-arithmetic_function(gl_GL_EXT_clip_volume_hint/0).
:-arithmetic_function(gl_GL_EXT_compiled_vertex_array/0).
:-arithmetic_function(gl_GL_EXTENSIONS/0).
:-arithmetic_function(gl_GL_EXT_paletted_texture/0).
:-arithmetic_function(gl_GL_EXT_point_parameters/0).
:-arithmetic_function(gl_GL_EXT_polygon_offset/0).
:-arithmetic_function(gl_GL_EXT_rescale_normal/0).
:-arithmetic_function(gl_GL_EXT_shared_texture_palette/0).
:-arithmetic_function(gl_GL_EXT_stencil_wrap/0).
:-arithmetic_function(gl_GL_EXT_texture3D/0).
:-arithmetic_function(gl_GL_EXT_texture_env_add/0).
:-arithmetic_function(gl_GL_EXT_texture_object/0).
:-arithmetic_function(gl_GL_EXT_vertex_array/0).
:-arithmetic_function(gl_GL_EYE_LINEAR/0).
:-arithmetic_function(gl_GL_EYE_PLANE/0).
:-arithmetic_function(gl_GL_FALSE/0).
:-arithmetic_function(gl_GL_FASTEST/0).
:-arithmetic_function(gl_GL_FEEDBACK/0).
:-arithmetic_function(gl_GL_FEEDBACK_BUFFER_POINTER/0).
:-arithmetic_function(gl_GL_FEEDBACK_BUFFER_SIZE/0).
:-arithmetic_function(gl_GL_FEEDBACK_BUFFER_TYPE/0).
:-arithmetic_function(gl_GL_FILL/0).
:-arithmetic_function(gl_GL_FLAT/0).
:-arithmetic_function(gl_GL_FLOAT/0).
:-arithmetic_function(gl_GL_FOG/0).
:-arithmetic_function(gl_GL_FOG_BIT/0).
:-arithmetic_function(gl_GL_FOG_COLOR/0).
:-arithmetic_function(gl_GL_FOG_DENSITY/0).
:-arithmetic_function(gl_GL_FOG_END/0).
:-arithmetic_function(gl_GL_FOG_HINT/0).
:-arithmetic_function(gl_GL_FOG_INDEX/0).
:-arithmetic_function(gl_GL_FOG_MODE/0).
:-arithmetic_function(gl_GL_FOG_START/0).
:-arithmetic_function(gl_GL_FRONT/0).
:-arithmetic_function(gl_GL_FRONT_AND_BACK/0).
:-arithmetic_function(gl_GL_FRONT_FACE/0).
:-arithmetic_function(gl_GL_FRONT_LEFT/0).
:-arithmetic_function(gl_GL_FRONT_RIGHT/0).
:-arithmetic_function(gl_GL_FUNC_ADD/0).
:-arithmetic_function(gl_GL_FUNC_ADD_EXT/0).
:-arithmetic_function(gl_GL_FUNC_REVERSE_SUBTRACT/0).
:-arithmetic_function(gl_GL_FUNC_REVERSE_SUBTRACT_EXT/0).
:-arithmetic_function(gl_GL_FUNC_SUBTRACT/0).
:-arithmetic_function(gl_GL_FUNC_SUBTRACT_EXT/0).
:-arithmetic_function(gl_GL_GEQUAL/0).
:-arithmetic_function(gl_GL_GREATER/0).
:-arithmetic_function(gl_GL_GREEN/0).
:-arithmetic_function(gl_GL_GREEN_BIAS/0).
:-arithmetic_function(gl_GL_GREEN_BITS/0).
:-arithmetic_function(gl_GL_GREEN_SCALE/0).
:-arithmetic_function(gl_GL_HINT_BIT/0).
:-arithmetic_function(gl_GL_HISTOGRAM/0).
:-arithmetic_function(gl_GL_HISTOGRAM_ALPHA_SIZE/0).
:-arithmetic_function(gl_GL_HISTOGRAM_BLUE_SIZE/0).
:-arithmetic_function(gl_GL_HISTOGRAM_FORMAT/0).
:-arithmetic_function(gl_GL_HISTOGRAM_GREEN_SIZE/0).
:-arithmetic_function(gl_GL_HISTOGRAM_LUMINANCE_SIZE/0).
:-arithmetic_function(gl_GL_HISTOGRAM_RED_SIZE/0).
:-arithmetic_function(gl_GL_HISTOGRAM_SINK/0).
:-arithmetic_function(gl_GL_HISTOGRAM_WIDTH/0).
:-arithmetic_function(gl_GL_HP_occlusion_test/0).
:-arithmetic_function(gl_GL_INCR/0).
:-arithmetic_function(gl_GL_INCR_WRAP_EXT/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_TYPE/0).
:-arithmetic_function(gl_GL_INDEX_ARRAY_TYPE_EXT/0).
:-arithmetic_function(gl_GL_INDEX_BITS/0).
:-arithmetic_function(gl_GL_INDEX_CLEAR_VALUE/0).
:-arithmetic_function(gl_GL_INDEX_LOGIC_OP/0).
:-arithmetic_function(gl_GL_INDEX_MODE/0).
:-arithmetic_function(gl_GL_INDEX_OFFSET/0).
:-arithmetic_function(gl_GL_INDEX_SHIFT/0).
:-arithmetic_function(gl_GL_INDEX_WRITEMASK/0).
:-arithmetic_function(gl_GL_INT/0).
:-arithmetic_function(gl_GL_INTENSITY/0).
:-arithmetic_function(gl_GL_INTENSITY12/0).
:-arithmetic_function(gl_GL_INTENSITY16/0).
:-arithmetic_function(gl_GL_INTENSITY4/0).
:-arithmetic_function(gl_GL_INTENSITY8/0).
:-arithmetic_function(gl_GL_INVALID_ENUM/0).
:-arithmetic_function(gl_GL_INVALID_OPERATION/0).
:-arithmetic_function(gl_GL_INVALID_VALUE/0).
:-arithmetic_function(gl_GL_INVERT/0).
:-arithmetic_function(gl_GL_KEEP/0).
:-arithmetic_function(gl_GL_LEFT/0).
:-arithmetic_function(gl_GL_LEQUAL/0).
:-arithmetic_function(gl_GL_LESS/0).
:-arithmetic_function(gl_GL_LIGHT0/0).
:-arithmetic_function(gl_GL_LIGHT1/0).
:-arithmetic_function(gl_GL_LIGHT2/0).
:-arithmetic_function(gl_GL_LIGHT3/0).
:-arithmetic_function(gl_GL_LIGHT4/0).
:-arithmetic_function(gl_GL_LIGHT5/0).
:-arithmetic_function(gl_GL_LIGHT6/0).
:-arithmetic_function(gl_GL_LIGHT7/0).
:-arithmetic_function(gl_GL_LIGHTING/0).
:-arithmetic_function(gl_GL_LIGHTING_BIT/0).
:-arithmetic_function(gl_GL_LIGHT_MODEL_AMBIENT/0).
:-arithmetic_function(gl_GL_LIGHT_MODEL_COLOR_CONTROL/0).
:-arithmetic_function(gl_GL_LIGHT_MODEL_LOCAL_VIEWER/0).
:-arithmetic_function(gl_GL_LIGHT_MODEL_TWO_SIDE/0).
:-arithmetic_function(gl_GL_LINE/0).
:-arithmetic_function(gl_GL_LINEAR/0).
:-arithmetic_function(gl_GL_LINEAR_ATTENUATION/0).
:-arithmetic_function(gl_GL_LINEAR_MIPMAP_LINEAR/0).
:-arithmetic_function(gl_GL_LINEAR_MIPMAP_NEAREST/0).
:-arithmetic_function(gl_GL_LINE_BIT/0).
:-arithmetic_function(gl_GL_LINE_LOOP/0).
:-arithmetic_function(gl_GL_LINE_RESET_TOKEN/0).
:-arithmetic_function(gl_GL_LINES/0).
:-arithmetic_function(gl_GL_LINE_SMOOTH/0).
:-arithmetic_function(gl_GL_LINE_SMOOTH_HINT/0).
:-arithmetic_function(gl_GL_LINE_STIPPLE/0).
:-arithmetic_function(gl_GL_LINE_STIPPLE_PATTERN/0).
:-arithmetic_function(gl_GL_LINE_STIPPLE_REPEAT/0).
:-arithmetic_function(gl_GL_LINE_STRIP/0).
:-arithmetic_function(gl_GL_LINE_TOKEN/0).
:-arithmetic_function(gl_GL_LINE_WIDTH/0).
:-arithmetic_function(gl_GL_LINE_WIDTH_GRANULARITY/0).
:-arithmetic_function(gl_GL_LINE_WIDTH_RANGE/0).
:-arithmetic_function(gl_GL_LIST_BASE/0).
:-arithmetic_function(gl_GL_LIST_BIT/0).
:-arithmetic_function(gl_GL_LIST_INDEX/0).
:-arithmetic_function(gl_GL_LIST_MODE/0).
:-arithmetic_function(gl_GL_LOAD/0).
:-arithmetic_function(gl_GL_LOGIC_OP/0).
:-arithmetic_function(gl_GL_LOGIC_OP_MODE/0).
:-arithmetic_function(gl_GL_LUMINANCE/0).
:-arithmetic_function(gl_GL_LUMINANCE12/0).
:-arithmetic_function(gl_GL_LUMINANCE12_ALPHA12/0).
:-arithmetic_function(gl_GL_LUMINANCE12_ALPHA4/0).
:-arithmetic_function(gl_GL_LUMINANCE16/0).
:-arithmetic_function(gl_GL_LUMINANCE16_ALPHA16/0).
:-arithmetic_function(gl_GL_LUMINANCE4/0).
:-arithmetic_function(gl_GL_LUMINANCE4_ALPHA4/0).
:-arithmetic_function(gl_GL_LUMINANCE6_ALPHA2/0).
:-arithmetic_function(gl_GL_LUMINANCE8/0).
:-arithmetic_function(gl_GL_LUMINANCE8_ALPHA8/0).
:-arithmetic_function(gl_GL_LUMINANCE_ALPHA/0).
:-arithmetic_function(gl_GL_MAP1_COLOR_4/0).
:-arithmetic_function(gl_GL_MAP1_GRID_DOMAIN/0).
:-arithmetic_function(gl_GL_MAP1_GRID_SEGMENTS/0).
:-arithmetic_function(gl_GL_MAP1_INDEX/0).
:-arithmetic_function(gl_GL_MAP1_NORMAL/0).
:-arithmetic_function(gl_GL_MAP1_TEXTURE_COORD_1/0).
:-arithmetic_function(gl_GL_MAP1_TEXTURE_COORD_2/0).
:-arithmetic_function(gl_GL_MAP1_TEXTURE_COORD_3/0).
:-arithmetic_function(gl_GL_MAP1_TEXTURE_COORD_4/0).
:-arithmetic_function(gl_GL_MAP1_VERTEX_3/0).
:-arithmetic_function(gl_GL_MAP1_VERTEX_4/0).
:-arithmetic_function(gl_GL_MAP2_COLOR_4/0).
:-arithmetic_function(gl_GL_MAP2_GRID_DOMAIN/0).
:-arithmetic_function(gl_GL_MAP2_GRID_SEGMENTS/0).
:-arithmetic_function(gl_GL_MAP2_INDEX/0).
:-arithmetic_function(gl_GL_MAP2_NORMAL/0).
:-arithmetic_function(gl_GL_MAP2_TEXTURE_COORD_1/0).
:-arithmetic_function(gl_GL_MAP2_TEXTURE_COORD_2/0).
:-arithmetic_function(gl_GL_MAP2_TEXTURE_COORD_3/0).
:-arithmetic_function(gl_GL_MAP2_TEXTURE_COORD_4/0).
:-arithmetic_function(gl_GL_MAP2_VERTEX_3/0).
:-arithmetic_function(gl_GL_MAP2_VERTEX_4/0).
:-arithmetic_function(gl_GL_MAP_COLOR/0).
:-arithmetic_function(gl_GL_MAP_STENCIL/0).
:-arithmetic_function(gl_GL_MATRIX_MODE/0).
:-arithmetic_function(gl_GL_MAX/0).
:-arithmetic_function(gl_GL_MAX_3D_TEXTURE_SIZE/0).
:-arithmetic_function(gl_GL_MAX_3D_TEXTURE_SIZE_EXT/0).
:-arithmetic_function(gl_GL_MAX_ATTRIB_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_CLIENT_ATTRIB_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_CLIP_PLANES/0).
:-arithmetic_function(gl_GL_MAX_COLOR_MATRIX_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_CONVOLUTION_HEIGHT/0).
:-arithmetic_function(gl_GL_MAX_CONVOLUTION_WIDTH/0).
:-arithmetic_function(gl_GL_MAX_ELEMENTS_INDICES/0).
:-arithmetic_function(gl_GL_MAX_ELEMENTS_VERTICES/0).
:-arithmetic_function(gl_GL_MAX_EVAL_ORDER/0).
:-arithmetic_function(gl_GL_MAX_EXT/0).
:-arithmetic_function(gl_GL_MAX_LIGHTS/0).
:-arithmetic_function(gl_GL_MAX_LIST_NESTING/0).
:-arithmetic_function(gl_GL_MAX_MODELVIEW_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_NAME_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_PIXEL_MAP_TABLE/0).
:-arithmetic_function(gl_GL_MAX_PROJECTION_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_TEXTURE_SIZE/0).
:-arithmetic_function(gl_GL_MAX_TEXTURE_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MAX_TEXTURE_UNITS_ARB/0).
:-arithmetic_function(gl_GL_MAX_VIEWPORT_DIMS/0).
:-arithmetic_function(gl_GL_MESA_resize_buffers/0).
:-arithmetic_function(gl_GL_MESA_window_pos/0).
:-arithmetic_function(gl_GL_MIN/0).
:-arithmetic_function(gl_GL_MIN_EXT/0).
:-arithmetic_function(gl_GL_MINMAX/0).
:-arithmetic_function(gl_GL_MINMAX_FORMAT/0).
:-arithmetic_function(gl_GL_MINMAX_SINK/0).
:-arithmetic_function(gl_GL_MODELVIEW/0).
:-arithmetic_function(gl_GL_MODELVIEW_MATRIX/0).
:-arithmetic_function(gl_GL_MODELVIEW_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_MODULATE/0).
:-arithmetic_function(gl_GL_MULT/0).
:-arithmetic_function(gl_GL_N3F_V3F/0).
:-arithmetic_function(gl_GL_NAME_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_NAND/0).
:-arithmetic_function(gl_GL_NEAREST/0).
:-arithmetic_function(gl_GL_NEAREST_MIPMAP_LINEAR/0).
:-arithmetic_function(gl_GL_NEAREST_MIPMAP_NEAREST/0).
:-arithmetic_function(gl_GL_NEVER/0).
:-arithmetic_function(gl_GL_NICEST/0).
:-arithmetic_function(gl_GL_NO_ERROR/0).
:-arithmetic_function(gl_GL_NONE/0).
:-arithmetic_function(gl_GL_NOOP/0).
:-arithmetic_function(gl_GL_NOR/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_TYPE/0).
:-arithmetic_function(gl_GL_NORMAL_ARRAY_TYPE_EXT/0).
:-arithmetic_function(gl_GL_NORMALIZE/0).
:-arithmetic_function(gl_GL_NORMAL_MAP_NV/0).
:-arithmetic_function(gl_GL_NOTEQUAL/0).
:-arithmetic_function(gl_GL_NV_texgen_reflection/0).
:-arithmetic_function(gl_GL_OBJECT_LINEAR/0).
:-arithmetic_function(gl_GL_OBJECT_PLANE/0).
:-arithmetic_function(gl_GL_OCCLUSION_TEST_HP/0).
:-arithmetic_function(gl_GL_OCCLUSION_TEST_RESULT_HP/0).
:-arithmetic_function(gl_GL_ONE/0).
:-arithmetic_function(gl_GL_ONE_MINUS_CONSTANT_ALPHA/0).
:-arithmetic_function(gl_GL_ONE_MINUS_CONSTANT_ALPHA_EXT/0).
:-arithmetic_function(gl_GL_ONE_MINUS_CONSTANT_COLOR/0).
:-arithmetic_function(gl_GL_ONE_MINUS_CONSTANT_COLOR_EXT/0).
:-arithmetic_function(gl_GL_ONE_MINUS_DST_ALPHA/0).
:-arithmetic_function(gl_GL_ONE_MINUS_DST_COLOR/0).
:-arithmetic_function(gl_GL_ONE_MINUS_SRC_ALPHA/0).
:-arithmetic_function(gl_GL_ONE_MINUS_SRC_COLOR/0).
:-arithmetic_function(gl_GL_OR/0).
:-arithmetic_function(gl_GL_ORDER/0).
:-arithmetic_function(gl_GL_OR_INVERTED/0).
:-arithmetic_function(gl_GL_OR_REVERSE/0).
:-arithmetic_function(gl_GL_OUT_OF_MEMORY/0).
:-arithmetic_function(gl_GL_PACK_ALIGNMENT/0).
:-arithmetic_function(gl_GL_PACK_IMAGE_HEIGHT/0).
:-arithmetic_function(gl_GL_PACK_IMAGE_HEIGHT_EXT/0).
:-arithmetic_function(gl_GL_PACK_LSB_FIRST/0).
:-arithmetic_function(gl_GL_PACK_ROW_LENGTH/0).
:-arithmetic_function(gl_GL_PACK_SKIP_IMAGES/0).
:-arithmetic_function(gl_GL_PACK_SKIP_IMAGES_EXT/0).
:-arithmetic_function(gl_GL_PACK_SKIP_PIXELS/0).
:-arithmetic_function(gl_GL_PACK_SKIP_ROWS/0).
:-arithmetic_function(gl_GL_PACK_SWAP_BYTES/0).
:-arithmetic_function(gl_GL_PASS_THROUGH_TOKEN/0).
:-arithmetic_function(gl_GL_PERSPECTIVE_CORRECTION_HINT/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_A_TO_A/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_A_TO_A_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_B_TO_B/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_B_TO_B_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_G_TO_G/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_G_TO_G_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_A/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_A_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_B/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_B_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_G/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_G_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_I/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_I_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_R/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_I_TO_R_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_R_TO_R/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_R_TO_R_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_S_TO_S/0).
:-arithmetic_function(gl_GL_PIXEL_MAP_S_TO_S_SIZE/0).
:-arithmetic_function(gl_GL_PIXEL_MODE_BIT/0).
:-arithmetic_function(gl_GL_POINT/0).
:-arithmetic_function(gl_GL_POINT_BIT/0).
:-arithmetic_function(gl_GL_POINT_FADE_THRESHOLD_SIZE_EXT/0).
:-arithmetic_function(gl_GL_POINTS/0).
:-arithmetic_function(gl_GL_POINT_SIZE/0).
:-arithmetic_function(gl_GL_POINT_SIZE_GRANULARITY/0).
:-arithmetic_function(gl_GL_POINT_SIZE_MAX_EXT/0).
:-arithmetic_function(gl_GL_POINT_SIZE_MIN_EXT/0).
:-arithmetic_function(gl_GL_POINT_SIZE_RANGE/0).
:-arithmetic_function(gl_GL_POINT_SMOOTH/0).
:-arithmetic_function(gl_GL_POINT_SMOOTH_HINT/0).
:-arithmetic_function(gl_GL_POINT_TOKEN/0).
:-arithmetic_function(gl_GL_POLYGON/0).
:-arithmetic_function(gl_GL_POLYGON_BIT/0).
:-arithmetic_function(gl_GL_POLYGON_MODE/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_BIAS_EXT/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_EXT/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_FACTOR/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_FACTOR_EXT/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_FILL/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_LINE/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_POINT/0).
:-arithmetic_function(gl_GL_POLYGON_OFFSET_UNITS/0).
:-arithmetic_function(gl_GL_POLYGON_SMOOTH/0).
:-arithmetic_function(gl_GL_POLYGON_SMOOTH_HINT/0).
:-arithmetic_function(gl_GL_POLYGON_STIPPLE/0).
:-arithmetic_function(gl_GL_POLYGON_STIPPLE_BIT/0).
:-arithmetic_function(gl_GL_POLYGON_TOKEN/0).
:-arithmetic_function(gl_GL_POSITION/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_ALPHA_BIAS/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_ALPHA_SCALE/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_BLUE_BIAS/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_BLUE_SCALE/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_GREEN_BIAS/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_GREEN_SCALE/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_RED_BIAS/0).
:-arithmetic_function(gl_GL_POST_COLOR_MATRIX_RED_SCALE/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_ALPHA_BIAS/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_ALPHA_SCALE/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_BLUE_BIAS/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_BLUE_SCALE/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_GREEN_BIAS/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_GREEN_SCALE/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_RED_BIAS/0).
:-arithmetic_function(gl_GL_POST_CONVOLUTION_RED_SCALE/0).
:-arithmetic_function(gl_GL_PROJECTION/0).
:-arithmetic_function(gl_GL_PROJECTION_MATRIX/0).
:-arithmetic_function(gl_GL_PROJECTION_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_PROXY_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_PROXY_HISTOGRAM/0).
:-arithmetic_function(gl_GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_PROXY_POST_CONVOLUTION_COLOR_TABLE/0).
:-arithmetic_function(gl_GL_PROXY_TEXTURE_1D/0).
:-arithmetic_function(gl_GL_PROXY_TEXTURE_2D/0).
:-arithmetic_function(gl_GL_PROXY_TEXTURE_3D/0).
:-arithmetic_function(gl_GL_PROXY_TEXTURE_3D_EXT/0).
:-arithmetic_function(gl_GL_Q/0).
:-arithmetic_function(gl_GL_QUADRATIC_ATTENUATION/0).
:-arithmetic_function(gl_GL_QUADS/0).
:-arithmetic_function(gl_GL_QUAD_STRIP/0).
:-arithmetic_function(gl_GL_R/0).
:-arithmetic_function(gl_GL_R3_G3_B2/0).
:-arithmetic_function(gl_GL_READ_BUFFER/0).
:-arithmetic_function(gl_GL_RED/0).
:-arithmetic_function(gl_GL_RED_BIAS/0).
:-arithmetic_function(gl_GL_RED_BITS/0).
:-arithmetic_function(gl_GL_RED_SCALE/0).
:-arithmetic_function(gl_GL_REDUCE/0).
:-arithmetic_function(gl_GL_REFLECTION_MAP_NV/0).
:-arithmetic_function(gl_GL_RENDER/0).
:-arithmetic_function(gl_GL_RENDERER/0).
:-arithmetic_function(gl_GL_RENDER_MODE/0).
:-arithmetic_function(gl_GL_REPEAT/0).
:-arithmetic_function(gl_GL_REPLACE/0).
:-arithmetic_function(gl_GL_REPLICATE_BORDER/0).
:-arithmetic_function(gl_GL_RESCALE_NORMAL/0).
:-arithmetic_function(gl_GL_RESCALE_NORMAL_EXT/0).
:-arithmetic_function(gl_GL_RETURN/0).
:-arithmetic_function(gl_GL_RGB/0).
:-arithmetic_function(gl_GL_RGB10/0).
:-arithmetic_function(gl_GL_RGB10_A2/0).
:-arithmetic_function(gl_GL_RGB12/0).
:-arithmetic_function(gl_GL_RGB16/0).
:-arithmetic_function(gl_GL_RGB4/0).
:-arithmetic_function(gl_GL_RGB5/0).
:-arithmetic_function(gl_GL_RGB5_A1/0).
:-arithmetic_function(gl_GL_RGB8/0).
:-arithmetic_function(gl_GL_RGBA/0).
:-arithmetic_function(gl_GL_RGBA12/0).
:-arithmetic_function(gl_GL_RGBA16/0).
:-arithmetic_function(gl_GL_RGBA2/0).
:-arithmetic_function(gl_GL_RGBA4/0).
:-arithmetic_function(gl_GL_RGBA8/0).
:-arithmetic_function(gl_GL_RGBA_MODE/0).
:-arithmetic_function(gl_GL_RIGHT/0).
:-arithmetic_function(gl_GL_S/0).
:-arithmetic_function(gl_GL_SCISSOR_BIT/0).
:-arithmetic_function(gl_GL_SCISSOR_BOX/0).
:-arithmetic_function(gl_GL_SCISSOR_TEST/0).
:-arithmetic_function(gl_GL_SELECT/0).
:-arithmetic_function(gl_GL_SELECTION_BUFFER_POINTER/0).
:-arithmetic_function(gl_GL_SELECTION_BUFFER_SIZE/0).
:-arithmetic_function(gl_GL_SEPARABLE_2D/0).
:-arithmetic_function(gl_GL_SEPARATE_SPECULAR_COLOR/0).
:-arithmetic_function(gl_GL_SET/0).
:-arithmetic_function(gl_GL_SGIS_texture_edge_clamp/0).
:-arithmetic_function(gl_GL_SHADE_MODEL/0).
:-arithmetic_function(gl_GL_SHARED_TEXTURE_PALETTE_EXT/0).
:-arithmetic_function(gl_GL_SHININESS/0).
:-arithmetic_function(gl_GL_SHORT/0).
:-arithmetic_function(gl_GL_SINgl_GLE_COLOR/0).
:-arithmetic_function(gl_GL_SMOOTH/0).
:-arithmetic_function(gl_GL_SMOOTH_LINE_WIDTH_GRANULARITY/0).
:-arithmetic_function(gl_GL_SMOOTH_LINE_WIDTH_RANGE/0).
:-arithmetic_function(gl_GL_SMOOTH_POINT_SIZE_GRANULARITY/0).
:-arithmetic_function(gl_GL_SMOOTH_POINT_SIZE_RANGE/0).
:-arithmetic_function(gl_GL_SPECULAR/0).
:-arithmetic_function(gl_GL_SPHERE_MAP/0).
:-arithmetic_function(gl_GL_SPOT_CUTOFF/0).
:-arithmetic_function(gl_GL_SPOT_DIRECTION/0).
:-arithmetic_function(gl_GL_SPOT_EXPONENT/0).
:-arithmetic_function(gl_GL_SRC_ALPHA/0).
:-arithmetic_function(gl_GL_SRC_ALPHA_SATURATE/0).
:-arithmetic_function(gl_GL_SRC_COLOR/0).
:-arithmetic_function(gl_GL_STACK_OVERFLOW/0).
:-arithmetic_function(gl_GL_STACK_UNDERFLOW/0).
:-arithmetic_function(gl_GL_STENCIL/0).
:-arithmetic_function(gl_GL_STENCIL_BITS/0).
:-arithmetic_function(gl_GL_STENCIL_BUFFER_BIT/0).
:-arithmetic_function(gl_GL_STENCIL_CLEAR_VALUE/0).
:-arithmetic_function(gl_GL_STENCIL_FAIL/0).
:-arithmetic_function(gl_GL_STENCIL_FUNC/0).
:-arithmetic_function(gl_GL_STENCIL_INDEX/0).
:-arithmetic_function(gl_GL_STENCIL_PASS_DEPTH_FAIL/0).
:-arithmetic_function(gl_GL_STENCIL_PASS_DEPTH_PASS/0).
:-arithmetic_function(gl_GL_STENCIL_REF/0).
:-arithmetic_function(gl_GL_STENCIL_TEST/0).
:-arithmetic_function(gl_GL_STENCIL_VALUE_MASK/0).
:-arithmetic_function(gl_GL_STENCIL_WRITEMASK/0).
:-arithmetic_function(gl_GL_STEREO/0).
:-arithmetic_function(gl_GL_SUBPIXEL_BITS/0).
:-arithmetic_function(gl_GL_T/0).
:-arithmetic_function(gl_GL_T2F_C3F_V3F/0).
:-arithmetic_function(gl_GL_T2F_C4F_N3F_V3F/0).
:-arithmetic_function(gl_GL_T2F_C4UB_V3F/0).
:-arithmetic_function(gl_GL_T2F_N3F_V3F/0).
:-arithmetic_function(gl_GL_T2F_V3F/0).
:-arithmetic_function(gl_GL_T4F_C4F_N3F_V4F/0).
:-arithmetic_function(gl_GL_T4F_V4F/0).
:-arithmetic_function(gl_GL_TABLE_TOO_LARGE/0).
:-arithmetic_function(gl_GL_TABLE_TOO_LARGE_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE/0).
:-arithmetic_function(gl_GL_TEXTURE0_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE10_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE11_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE12_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE13_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE14_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE15_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE16_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE17_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE18_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE19_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE1_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE_1D/0).
:-arithmetic_function(gl_GL_TEXTURE_1D_BINDING_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE20_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE21_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE22_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE23_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE24_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE25_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE26_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE27_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE28_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE29_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE2_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE_2D/0).
:-arithmetic_function(gl_GL_TEXTURE_2D_BINDING_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE30_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE31_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE3_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE_3D/0).
:-arithmetic_function(gl_GL_TEXTURE_3D_BINDING_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_3D_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE4_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE5_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE6_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE7_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE8_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE9_ARB/0).
:-arithmetic_function(gl_GL_TEXTURE_ALPHA_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_BASE_LEVEL/0).
:-arithmetic_function(gl_GL_TEXTURE_BINDING_1D/0).
:-arithmetic_function(gl_GL_TEXTURE_BINDING_2D/0).
:-arithmetic_function(gl_GL_TEXTURE_BINDING_3D/0).
:-arithmetic_function(gl_GL_TEXTURE_BIT/0).
:-arithmetic_function(gl_GL_TEXTURE_BLUE_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_BORDER/0).
:-arithmetic_function(gl_GL_TEXTURE_BORDER_COLOR/0).
:-arithmetic_function(gl_GL_TEXTURE_COMPONENTS/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_SIZE_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_TYPE/0).
:-arithmetic_function(gl_GL_TEXTURE_COORD_ARRAY_TYPE_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_DEPTH/0).
:-arithmetic_function(gl_GL_TEXTURE_DEPTH_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_ENV/0).
:-arithmetic_function(gl_GL_TEXTURE_ENV_COLOR/0).
:-arithmetic_function(gl_GL_TEXTURE_ENV_MODE/0).
:-arithmetic_function(gl_GL_TEXTURE_GEN_MODE/0).
:-arithmetic_function(gl_GL_TEXTURE_GEN_Q/0).
:-arithmetic_function(gl_GL_TEXTURE_GEN_R/0).
:-arithmetic_function(gl_GL_TEXTURE_GEN_S/0).
:-arithmetic_function(gl_GL_TEXTURE_GEN_T/0).
:-arithmetic_function(gl_GL_TEXTURE_GREEN_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_HEIGHT/0).
:-arithmetic_function(gl_GL_TEXTURE_INDEX_SIZE_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_INTENSITY_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_INTERNAL_FORMAT/0).
:-arithmetic_function(gl_GL_TEXTURE_LUMINANCE_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_MAG_FILTER/0).
:-arithmetic_function(gl_GL_TEXTURE_MATRIX/0).
:-arithmetic_function(gl_GL_TEXTURE_MAX_LEVEL/0).
:-arithmetic_function(gl_GL_TEXTURE_MAX_LOD/0).
:-arithmetic_function(gl_GL_TEXTURE_MIN_FILTER/0).
:-arithmetic_function(gl_GL_TEXTURE_MIN_LOD/0).
:-arithmetic_function(gl_GL_TEXTURE_PRIORITY/0).
:-arithmetic_function(gl_GL_TEXTURE_PRIORITY_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_RED_SIZE/0).
:-arithmetic_function(gl_GL_TEXTURE_RESIDENT/0).
:-arithmetic_function(gl_GL_TEXTURE_RESIDENT_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_STACK_DEPTH/0).
:-arithmetic_function(gl_GL_TEXTURE_WIDTH/0).
:-arithmetic_function(gl_GL_TEXTURE_WRAP_R/0).
:-arithmetic_function(gl_GL_TEXTURE_WRAP_R_EXT/0).
:-arithmetic_function(gl_GL_TEXTURE_WRAP_S/0).
:-arithmetic_function(gl_GL_TEXTURE_WRAP_T/0).
:-arithmetic_function(gl_GL_TRANSFORM_BIT/0).
:-arithmetic_function(gl_GL_TRIANGLE_FAN/0).
:-arithmetic_function(gl_GL_TRIANGLES/0).
:-arithmetic_function(gl_GL_TRIANGLE_STRIP/0).
:-arithmetic_function(gl_GL_TRUE/0).
:-arithmetic_function(gl_GL_UNPACK_ALIGNMENT/0).
:-arithmetic_function(gl_GL_UNPACK_IMAGE_HEIGHT/0).
:-arithmetic_function(gl_GL_UNPACK_IMAGE_HEIGHT_EXT/0).
:-arithmetic_function(gl_GL_UNPACK_LSB_FIRST/0).
:-arithmetic_function(gl_GL_UNPACK_ROW_LENGTH/0).
:-arithmetic_function(gl_GL_UNPACK_SKIP_IMAGES/0).
:-arithmetic_function(gl_GL_UNPACK_SKIP_IMAGES_EXT/0).
:-arithmetic_function(gl_GL_UNPACK_SKIP_PIXELS/0).
:-arithmetic_function(gl_GL_UNPACK_SKIP_ROWS/0).
:-arithmetic_function(gl_GL_UNPACK_SWAP_BYTES/0).
:-arithmetic_function(gl_GL_UNSIGNED_BYTE/0).
:-arithmetic_function(gl_GL_UNSIGNED_BYTE_2_3_3_REV/0).
:-arithmetic_function(gl_GL_UNSIGNED_BYTE_3_3_2/0).
:-arithmetic_function(gl_GL_UNSIGNED_INT/0).
:-arithmetic_function(gl_GL_UNSIGNED_INT_10_10_10_2/0).
:-arithmetic_function(gl_GL_UNSIGNED_INT_2_10_10_10_REV/0).
:-arithmetic_function(gl_GL_UNSIGNED_INT_8_8_8_8/0).
:-arithmetic_function(gl_GL_UNSIGNED_INT_8_8_8_8_REV/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_1_5_5_5_REV/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_4_4_4_4/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_4_4_4_4_REV/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_5_5_5_1/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_5_6_5/0).
:-arithmetic_function(gl_GL_UNSIGNED_SHORT_5_6_5_REV/0).
:-arithmetic_function(gl_GL_V2F/0).
:-arithmetic_function(gl_GL_V3F/0).
:-arithmetic_function(gl_GL_VENDOR/0).
:-arithmetic_function(gl_GL_VERSION/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_COUNT_EXT/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_EXT/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_POINTER/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_POINTER_EXT/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_SIZE/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_SIZE_EXT/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_STRIDE/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_STRIDE_EXT/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_TYPE/0).
:-arithmetic_function(gl_GL_VERTEX_ARRAY_TYPE_EXT/0).
:-arithmetic_function(gl_GL_VIEWPORT/0).
:-arithmetic_function(gl_GL_VIEWPORT_BIT/0).
:-arithmetic_function(gl_GL_XOR/0).
:-arithmetic_function(gl_GL_ZERO/0).
:-arithmetic_function(gl_GL_ZOOM_X/0).
:-arithmetic_function(gl_GL_ZOOM_Y/0).
gl_GL_2_BYTES(0x1407).
gl_GL_2D(0x0600).
gl_GL_3_BYTES(0x1408).
gl_GL_3D(0x0601).
gl_GL_3D_COLOR(0x0602).
gl_GL_3D_COLOR_TEXTURE(0x0603).
gl_GL_4_BYTES(0x1409).
gl_GL_4D_COLOR_TEXTURE(0x0604).
gl_GL_ABGR_EXT(0x8000).
gl_GL_ACCUM(0x0100).
gl_GL_ACCUM_ALPHA_BITS(0x0D5B).
gl_GL_ACCUM_BLUE_BITS(0x0D5A).
gl_GL_ACCUM_BUFFER_BIT(0x00000200).
gl_GL_ACCUM_CLEAR_VALUE(0x0B80).
gl_GL_ACCUM_GREEN_BITS(0x0D59).
gl_GL_ACCUM_RED_BITS(0x0D58).
gl_GL_ACTIVE_TEXTURE_ARB(0x84E0).
gl_GL_ADD(0x0104).
gl_GL_ALIASED_LINE_WIDTH_RANGE(0x846E).
gl_GL_ALIASED_POINT_SIZE_RANGE(0x846D).
gl_GL_ALL_ATTRIB_BITS(0x000FFFFF).
gl_GL_ALL_CLIENT_ATTRIB_BITS(0xFFFFFFFF).
gl_GL_ALPHA(0x1906).
gl_GL_ALPHA12(0x803D).
gl_GL_ALPHA16(0x803E).
gl_GL_ALPHA4(0x803B).
gl_GL_ALPHA8(0x803C).
gl_GL_ALPHA_BIAS(0x0D1D).
gl_GL_ALPHA_BITS(0x0D55).
gl_GL_ALPHA_SCALE(0x0D1C).
gl_GL_ALPHA_TEST(0x0BC0).
gl_GL_ALPHA_TEST_FUNC(0x0BC1).
gl_GL_ALPHA_TEST_REF(0x0BC2).
gl_GL_ALWAYS(0x0207).
gl_GL_AMBIENT(0x1200).
gl_GL_AMBIENT_AND_DIFFUSE(0x1602).
gl_GL_AND(0x1501).
gl_GL_AND_INVERTED(0x1504).
gl_GL_AND_REVERSE(0x1502).
gl_GL_ARB_multitexture(1).
gl_GL_ARRAY_ELEMENT_LOCK_COUNT_EXT(0x81A9).
gl_GL_ARRAY_ELEMENT_LOCK_FIRST_EXT(0x81A8).
gl_GL_ATTRIB_STACK_DEPTH(0x0BB0).
gl_GL_AUTO_NORMAL(0x0D80).
gl_GL_AUX0(0x0409).
gl_GL_AUX1(0x040A).
gl_GL_AUX2(0x040B).
gl_GL_AUX3(0x040C).
gl_GL_AUX_BUFFERS(0x0C00).
gl_GL_BACK(0x0405).
gl_GL_BACK_LEFT(0x0402).
gl_GL_BACK_RIGHT(0x0403).
gl_GL_BGR(0x80E0).
gl_GL_BGRA(0x80E1).
gl_GL_BITMAP(0x1A00).
gl_GL_BITMAP_TOKEN(0x0704).
gl_GL_BLEND(0x0BE2).
gl_GL_BLEND_COLOR(0x8005).
gl_GL_BLEND_COLOR_EXT(0x8005).
gl_GL_BLEND_DST(0x0BE0).
gl_GL_BLEND_EQUATION(0x8009).
gl_GL_BLEND_EQUATION_EXT(0x8009).
gl_GL_BLEND_SRC(0x0BE1).
gl_GL_BLUE(0x1905).
gl_GL_BLUE_BIAS(0x0D1B).
gl_GL_BLUE_BITS(0x0D54).
gl_GL_BLUE_SCALE(0x0D1A).
gl_GL_BYTE(0x1400).
gl_GL_C3F_V3F(0x2A24).
gl_GL_C4F_N3F_V3F(0x2A26).
gl_GL_C4UB_V2F(0x2A22).
gl_GL_C4UB_V3F(0x2A23).
gl_GL_CCW(0x0901).
gl_GL_CLAMP(0x2900).
gl_GL_CLAMP_TO_EDGE(0x812F).
gl_GL_CLAMP_TO_EDGE_SGIS(0x812F).
gl_GL_CLEAR(0x1500).
gl_GL_CLIENT_ACTIVE_TEXTURE_ARB(0x84E1).
gl_GL_CLIENT_ATTRIB_STACK_DEPTH(0x0BB1).
gl_GL_CLIENT_PIXEL_STORE_BIT(0x00000001).
gl_GL_CLIENT_VERTEX_ARRAY_BIT(0x00000002).
gl_GL_CLIP_PLANE0(0x3000).
gl_GL_CLIP_PLANE1(0x3001).
gl_GL_CLIP_PLANE2(0x3002).
gl_GL_CLIP_PLANE3(0x3003).
gl_GL_CLIP_PLANE4(0x3004).
gl_GL_CLIP_PLANE5(0x3005).
gl_GL_CLIP_VOLUME_CLIPPING_HINT_EXT(0x80F0).
gl_GL_COEFF(0x0A00).
gl_GL_COLOR(0x1800).
gl_GL_COLOR_ARRAY(0x8076).
gl_GL_COLOR_ARRAY_COUNT_EXT(0x8084).
gl_GL_COLOR_ARRAY_EXT(0x8076).
gl_GL_COLOR_ARRAY_POINTER(0x8090).
gl_GL_COLOR_ARRAY_POINTER_EXT(0x8090).
gl_GL_COLOR_ARRAY_SIZE(0x8081).
gl_GL_COLOR_ARRAY_SIZE_EXT(0x8081).
gl_GL_COLOR_ARRAY_STRIDE(0x8083).
gl_GL_COLOR_ARRAY_STRIDE_EXT(0x8083).
gl_GL_COLOR_ARRAY_TYPE(0x8082).
gl_GL_COLOR_ARRAY_TYPE_EXT(0x8082).
gl_GL_COLOR_BUFFER_BIT(0x00004000).
gl_GL_COLOR_CLEAR_VALUE(0x0C22).
gl_GL_COLOR_INDEX(0x1900).
gl_GL_COLOR_INDEX12_EXT(0x80E6).
gl_GL_COLOR_INDEX16_EXT(0x80E7).
gl_GL_COLOR_INDEX1_EXT(0x80E2).
gl_GL_COLOR_INDEX2_EXT(0x80E3).
gl_GL_COLOR_INDEX4_EXT(0x80E4).
gl_GL_COLOR_INDEX8_EXT(0x80E5).
gl_GL_COLOR_INDEXES(0x1603).
gl_GL_COLOR_LOGIC_OP(0x0BF2).
gl_GL_COLOR_MATERIAL(0x0B57).
gl_GL_COLOR_MATERIAL_FACE(0x0B55).
gl_GL_COLOR_MATERIAL_PARAMETER(0x0B56).
gl_GL_COLOR_MATRIX(0x80B1).
gl_GL_COLOR_MATRIX_STACK_DEPTH(0x80B2).
gl_GL_COLOR_TABLE(0x80D0).
gl_GL_COLOR_TABLE_ALPHA_SIZE(0x80DD).
gl_GL_COLOR_TABLE_ALPHA_SIZE_EXT(0x80DD).
gl_GL_COLOR_TABLE_BIAS(0x80D7).
gl_GL_COLOR_TABLE_BLUE_SIZE(0x80DC).
gl_GL_COLOR_TABLE_BLUE_SIZE_EXT(0x80DC).
gl_GL_COLOR_TABLE_FORMAT(0x80D8).
gl_GL_COLOR_TABLE_FORMAT_EXT(0x80D8).
gl_GL_COLOR_TABLE_GREEN_SIZE(0x80DB).
gl_GL_COLOR_TABLE_GREEN_SIZE_EXT(0x80DB).
gl_GL_COLOR_TABLE_INTENSITY_SIZE(0x80DF).
gl_GL_COLOR_TABLE_INTENSITY_SIZE_EXT(0x80DF).
gl_GL_COLOR_TABLE_LUMINANCE_SIZE(0x80DE).
gl_GL_COLOR_TABLE_LUMINANCE_SIZE_EXT(0x80DE).
gl_GL_COLOR_TABLE_RED_SIZE(0x80DA).
gl_GL_COLOR_TABLE_RED_SIZE_EXT(0x80DA).
gl_GL_COLOR_TABLE_SCALE(0x80D6).
gl_GL_COLOR_TABLE_WIDTH(0x80D9).
gl_GL_COLOR_TABLE_WIDTH_EXT(0x80D9).
gl_GL_COLOR_WRITEMASK(0x0C23).
gl_GL_COMPILE(0x1300).
gl_GL_COMPILE_AND_EXECUTE(0x1301).
gl_GL_CONSTANT_ALPHA(0x8003).
gl_GL_CONSTANT_ALPHA_EXT(0x8003).
gl_GL_CONSTANT_ATTENUATION(0x1207).
gl_GL_CONSTANT_BORDER(0x8151).
gl_GL_CONSTANT_COLOR(0x8001).
gl_GL_CONSTANT_COLOR_EXT(0x8001).
gl_GL_CONVOLUTION_1D(0x8010).
gl_GL_CONVOLUTION_2D(0x8011).
gl_GL_CONVOLUTION_BORDER_COLOR(0x8154).
gl_GL_CONVOLUTION_BORDER_MODE(0x8013).
gl_GL_CONVOLUTION_FILTER_BIAS(0x8015).
gl_GL_CONVOLUTION_FILTER_SCALE(0x8014).
gl_GL_CONVOLUTION_FORMAT(0x8017).
gl_GL_CONVOLUTION_HEIGHT(0x8019).
gl_GL_CONVOLUTION_WIDTH(0x8018).
gl_GL_COPY(0x1503).
gl_GL_COPY_INVERTED(0x150C).
gl_GL_COPY_PIXEL_TOKEN(0x0706).
gl_GL_CULL_FACE(0x0B44).
gl_GL_CULL_FACE_MODE(0x0B45).
gl_GL_CURRENT_BIT(0x00000001).
gl_GL_CURRENT_COLOR(0x0B00).
gl_GL_CURRENT_INDEX(0x0B01).
gl_GL_CURRENT_NORMAL(0x0B02).
gl_GL_CURRENT_RASTER_COLOR(0x0B04).
gl_GL_CURRENT_RASTER_DISTANCE(0x0B09).
gl_GL_CURRENT_RASTER_INDEX(0x0B05).
gl_GL_CURRENT_RASTER_POSITION(0x0B07).
gl_GL_CURRENT_RASTER_POSITION_VALID(0x0B08).
gl_GL_CURRENT_RASTER_TEXTURE_COORDS(0x0B06).
gl_GL_CURRENT_TEXTURE_COORDS(0x0B03).
gl_GL_CW(0x0900).
gl_GL_DECAL(0x2101).
gl_GL_DECR(0x1E03).
gl_GL_DECR_WRAP_EXT(0x8508).
gl_GL_DEPTH(0x1801).
gl_GL_DEPTH_BIAS(0x0D1F).
gl_GL_DEPTH_BITS(0x0D56).
gl_GL_DEPTH_BUFFER_BIT(0x00000100).
gl_GL_DEPTH_CLEAR_VALUE(0x0B73).
gl_GL_DEPTH_COMPONENT(0x1902).
gl_GL_DEPTH_FUNC(0x0B74).
gl_GL_DEPTH_RANGE(0x0B70).
gl_GL_DEPTH_SCALE(0x0D1E).
gl_GL_DEPTH_TEST(0x0B71).
gl_GL_DEPTH_WRITEMASK(0x0B72).
gl_GL_DIFFUSE(0x1201).
gl_GL_DISTANCE_ATTENUATION_EXT(0x8129).
gl_GL_DITHER(0x0BD0).
gl_GL_DOMAIN(0x0A02).
gl_GL_DONT_CARE(0x1100).
gl_GL_DOUBLE(0x140A).
gl_GL_DOUBLEBUFFER(0x0C32).
gl_GL_DRAW_BUFFER(0x0C01).
gl_GL_DRAW_PIXEL_TOKEN(0x0705).
gl_GL_DST_ALPHA(0x0304).
gl_GL_DST_COLOR(0x0306).
gl_GL_EDGE_FLAG(0x0B43).
gl_GL_EDGE_FLAG_ARRAY(0x8079).
gl_GL_EDGE_FLAG_ARRAY_COUNT_EXT(0x808D).
gl_GL_EDGE_FLAG_ARRAY_EXT(0x8079).
gl_GL_EDGE_FLAG_ARRAY_POINTER(0x8093).
gl_GL_EDGE_FLAG_ARRAY_POINTER_EXT(0x8093).
gl_GL_EDGE_FLAG_ARRAY_STRIDE(0x808C).
gl_GL_EDGE_FLAG_ARRAY_STRIDE_EXT(0x808C).
gl_GL_EMISSION(0x1600).
gl_GL_ENABLE_BIT(0x00002000).
gl_GL_EQUAL(0x0202).
gl_GL_EQUIV(0x1509).
gl_GL_EVAL_BIT(0x00010000).
gl_GL_EXP(0x0800).
gl_GL_EXP2(0x0801).
gl_GL_EXT_abgr(1).
gl_GL_EXT_blend_color(1).
gl_GL_EXT_blend_logic_op(1).
gl_GL_EXT_blend_minmax(1).
gl_GL_EXT_blend_subtract(1).
gl_GL_EXT_clip_volume_hint(1).
gl_GL_EXT_compiled_vertex_array(1).
gl_GL_EXTENSIONS(0x1F03).
gl_GL_EXT_paletted_texture(1).
gl_GL_EXT_point_parameters(1).
gl_GL_EXT_polygon_offset(1).
gl_GL_EXT_rescale_normal(1).
gl_GL_EXT_shared_texture_palette(1).
gl_GL_EXT_stencil_wrap(1).
gl_GL_EXT_texture3D(1).
gl_GL_EXT_texture_env_add(1).
gl_GL_EXT_texture_object(1).
gl_GL_EXT_vertex_array(1).
gl_GL_EYE_LINEAR(0x2400).
gl_GL_EYE_PLANE(0x2502).
gl_GL_FALSE(0x0).
gl_GL_FASTEST(0x1101).
gl_GL_FEEDBACK(0x1C01).
gl_GL_FEEDBACK_BUFFER_POINTER(0x0DF0).
gl_GL_FEEDBACK_BUFFER_SIZE(0x0DF1).
gl_GL_FEEDBACK_BUFFER_TYPE(0x0DF2).
gl_GL_FILL(0x1B02).
gl_GL_FLAT(0x1D00).
gl_GL_FLOAT(0x1406).
gl_GL_FOG(0x0B60).
gl_GL_FOG_BIT(0x00000080).
gl_GL_FOG_COLOR(0x0B66).
gl_GL_FOG_DENSITY(0x0B62).
gl_GL_FOG_END(0x0B64).
gl_GL_FOG_HINT(0x0C54).
gl_GL_FOG_INDEX(0x0B61).
gl_GL_FOG_MODE(0x0B65).
gl_GL_FOG_START(0x0B63).
gl_GL_FRONT(0x0404).
gl_GL_FRONT_AND_BACK(0x0408).
gl_GL_FRONT_FACE(0x0B46).
gl_GL_FRONT_LEFT(0x0400).
gl_GL_FRONT_RIGHT(0x0401).
gl_GL_FUNC_ADD(0x8006).
gl_GL_FUNC_ADD_EXT(0x8006).
gl_GL_FUNC_REVERSE_SUBTRACT(0x800B).
gl_GL_FUNC_REVERSE_SUBTRACT_EXT(0x800B).
gl_GL_FUNC_SUBTRACT(0x800A).
gl_GL_FUNC_SUBTRACT_EXT(0x800A).
gl_GL_GEQUAL(0x0206).
gl_GL_GREATER(0x0204).
gl_GL_GREEN(0x1904).
gl_GL_GREEN_BIAS(0x0D19).
gl_GL_GREEN_BITS(0x0D53).
gl_GL_GREEN_SCALE(0x0D18).
gl_GL_HINT_BIT(0x00008000).
gl_GL_HISTOGRAM(0x8024).
gl_GL_HISTOGRAM_ALPHA_SIZE(0x802B).
gl_GL_HISTOGRAM_BLUE_SIZE(0x802A).
gl_GL_HISTOGRAM_FORMAT(0x8027).
gl_GL_HISTOGRAM_GREEN_SIZE(0x8029).
gl_GL_HISTOGRAM_LUMINANCE_SIZE(0x802C).
gl_GL_HISTOGRAM_RED_SIZE(0x8028).
gl_GL_HISTOGRAM_SINK(0x802D).
gl_GL_HISTOGRAM_WIDTH(0x8026).
gl_GL_HP_occlusion_test(1).
gl_GL_INCR(0x1E02).
gl_GL_INCR_WRAP_EXT(0x8507).
gl_GL_INDEX_ARRAY(0x8077).
gl_GL_INDEX_ARRAY_COUNT_EXT(0x8087).
gl_GL_INDEX_ARRAY_EXT(0x8077).
gl_GL_INDEX_ARRAY_POINTER(0x8091).
gl_GL_INDEX_ARRAY_POINTER_EXT(0x8091).
gl_GL_INDEX_ARRAY_STRIDE(0x8086).
gl_GL_INDEX_ARRAY_STRIDE_EXT(0x8086).
gl_GL_INDEX_ARRAY_TYPE(0x8085).
gl_GL_INDEX_ARRAY_TYPE_EXT(0x8085).
gl_GL_INDEX_BITS(0x0D51).
gl_GL_INDEX_CLEAR_VALUE(0x0C20).
gl_GL_INDEX_LOGIC_OP(0x0BF1).
gl_GL_INDEX_MODE(0x0C30).
gl_GL_INDEX_OFFSET(0x0D13).
gl_GL_INDEX_SHIFT(0x0D12).
gl_GL_INDEX_WRITEMASK(0x0C21).
gl_GL_INT(0x1404).
gl_GL_INTENSITY(0x8049).
gl_GL_INTENSITY12(0x804C).
gl_GL_INTENSITY16(0x804D).
gl_GL_INTENSITY4(0x804A).
gl_GL_INTENSITY8(0x804B).
gl_GL_INVALID_ENUM(0x0500).
gl_GL_INVALID_OPERATION(0x0502).
gl_GL_INVALID_VALUE(0x0501).
gl_GL_INVERT(0x150A).
gl_GL_KEEP(0x1E00).
gl_GL_LEFT(0x0406).
gl_GL_LEQUAL(0x0203).
gl_GL_LESS(0x0201).
gl_GL_LIGHT0(0x4000).
gl_GL_LIGHT1(0x4001).
gl_GL_LIGHT2(0x4002).
gl_GL_LIGHT3(0x4003).
gl_GL_LIGHT4(0x4004).
gl_GL_LIGHT5(0x4005).
gl_GL_LIGHT6(0x4006).
gl_GL_LIGHT7(0x4007).
gl_GL_LIGHTING(0x0B50).
gl_GL_LIGHTING_BIT(0x00000040).
gl_GL_LIGHT_MODEL_AMBIENT(0x0B53).
gl_GL_LIGHT_MODEL_COLOR_CONTROL(0x81F8).
gl_GL_LIGHT_MODEL_LOCAL_VIEWER(0x0B51).
gl_GL_LIGHT_MODEL_TWO_SIDE(0x0B52).
gl_GL_LINE(0x1B01).
gl_GL_LINEAR(0x2601).
gl_GL_LINEAR_ATTENUATION(0x1208).
gl_GL_LINEAR_MIPMAP_LINEAR(0x2703).
gl_GL_LINEAR_MIPMAP_NEAREST(0x2701).
gl_GL_LINE_BIT(0x00000004).
gl_GL_LINE_LOOP(0x0002).
gl_GL_LINE_RESET_TOKEN(0x0707).
gl_GL_LINES(0x0001).
gl_GL_LINE_SMOOTH(0x0B20).
gl_GL_LINE_SMOOTH_HINT(0x0C52).
gl_GL_LINE_STIPPLE(0x0B24).
gl_GL_LINE_STIPPLE_PATTERN(0x0B25).
gl_GL_LINE_STIPPLE_REPEAT(0x0B26).
gl_GL_LINE_STRIP(0x0003).
gl_GL_LINE_TOKEN(0x0702).
gl_GL_LINE_WIDTH(0x0B21).
gl_GL_LINE_WIDTH_GRANULARITY(0x0B23).
gl_GL_LINE_WIDTH_RANGE(0x0B22).
gl_GL_LIST_BASE(0x0B32).
gl_GL_LIST_BIT(0x00020000).
gl_GL_LIST_INDEX(0x0B33).
gl_GL_LIST_MODE(0x0B30).
gl_GL_LOAD(0x0101).
gl_GL_LOGIC_OP(0x0BF1).
gl_GL_LOGIC_OP_MODE(0x0BF0).
gl_GL_LUMINANCE(0x1909).
gl_GL_LUMINANCE12(0x8041).
gl_GL_LUMINANCE12_ALPHA12(0x8047).
gl_GL_LUMINANCE12_ALPHA4(0x8046).
gl_GL_LUMINANCE16(0x8042).
gl_GL_LUMINANCE16_ALPHA16(0x8048).
gl_GL_LUMINANCE4(0x803F).
gl_GL_LUMINANCE4_ALPHA4(0x8043).
gl_GL_LUMINANCE6_ALPHA2(0x8044).
gl_GL_LUMINANCE8(0x8040).
gl_GL_LUMINANCE8_ALPHA8(0x8045).
gl_GL_LUMINANCE_ALPHA(0x190A).
gl_GL_MAP1_COLOR_4(0x0D90).
gl_GL_MAP1_GRID_DOMAIN(0x0DD0).
gl_GL_MAP1_GRID_SEGMENTS(0x0DD1).
gl_GL_MAP1_INDEX(0x0D91).
gl_GL_MAP1_NORMAL(0x0D92).
gl_GL_MAP1_TEXTURE_COORD_1(0x0D93).
gl_GL_MAP1_TEXTURE_COORD_2(0x0D94).
gl_GL_MAP1_TEXTURE_COORD_3(0x0D95).
gl_GL_MAP1_TEXTURE_COORD_4(0x0D96).
gl_GL_MAP1_VERTEX_3(0x0D97).
gl_GL_MAP1_VERTEX_4(0x0D98).
gl_GL_MAP2_COLOR_4(0x0DB0).
gl_GL_MAP2_GRID_DOMAIN(0x0DD2).
gl_GL_MAP2_GRID_SEGMENTS(0x0DD3).
gl_GL_MAP2_INDEX(0x0DB1).
gl_GL_MAP2_NORMAL(0x0DB2).
gl_GL_MAP2_TEXTURE_COORD_1(0x0DB3).
gl_GL_MAP2_TEXTURE_COORD_2(0x0DB4).
gl_GL_MAP2_TEXTURE_COORD_3(0x0DB5).
gl_GL_MAP2_TEXTURE_COORD_4(0x0DB6).
gl_GL_MAP2_VERTEX_3(0x0DB7).
gl_GL_MAP2_VERTEX_4(0x0DB8).
gl_GL_MAP_COLOR(0x0D10).
gl_GL_MAP_STENCIL(0x0D11).
gl_GL_MATRIX_MODE(0x0BA0).
gl_GL_MAX(0x8008).
gl_GL_MAX_3D_TEXTURE_SIZE(0x8073).
gl_GL_MAX_3D_TEXTURE_SIZE_EXT(0x8073).
gl_GL_MAX_ATTRIB_STACK_DEPTH(0x0D35).
gl_GL_MAX_CLIENT_ATTRIB_STACK_DEPTH(0x0D3B).
gl_GL_MAX_CLIP_PLANES(0x0D32).
gl_GL_MAX_COLOR_MATRIX_STACK_DEPTH(0x80B3).
gl_GL_MAX_CONVOLUTION_HEIGHT(0x801B).
gl_GL_MAX_CONVOLUTION_WIDTH(0x801A).
gl_GL_MAX_ELEMENTS_INDICES(0x80E9).
gl_GL_MAX_ELEMENTS_VERTICES(0x80E8).
gl_GL_MAX_EVAL_ORDER(0x0D30).
gl_GL_MAX_EXT(0x8008).
gl_GL_MAX_LIGHTS(0x0D31).
gl_GL_MAX_LIST_NESTING(0x0B31).
gl_GL_MAX_MODELVIEW_STACK_DEPTH(0x0D36).
gl_GL_MAX_NAME_STACK_DEPTH(0x0D37).
gl_GL_MAX_PIXEL_MAP_TABLE(0x0D34).
gl_GL_MAX_PROJECTION_STACK_DEPTH(0x0D38).
gl_GL_MAX_TEXTURE_SIZE(0x0D33).
gl_GL_MAX_TEXTURE_STACK_DEPTH(0x0D39).
gl_GL_MAX_TEXTURE_UNITS_ARB(0x84E2).
gl_GL_MAX_VIEWPORT_DIMS(0x0D3A).
gl_GL_MESA_resize_buffers(1).
gl_GL_MESA_window_pos(1).
gl_GL_MIN(0x8007).
gl_GL_MIN_EXT(0x8007).
gl_GL_MINMAX(0x802E).
gl_GL_MINMAX_FORMAT(0x802F).
gl_GL_MINMAX_SINK(0x8030).
gl_GL_MODELVIEW(0x1700).
gl_GL_MODELVIEW_MATRIX(0x0BA6).
gl_GL_MODELVIEW_STACK_DEPTH(0x0BA3).
gl_GL_MODULATE(0x2100).
gl_GL_MULT(0x0103).
gl_GL_N3F_V3F(0x2A25).
gl_GL_NAME_STACK_DEPTH(0x0D70).
gl_GL_NAND(0x150E).
gl_GL_NEAREST(0x2600).
gl_GL_NEAREST_MIPMAP_LINEAR(0x2702).
gl_GL_NEAREST_MIPMAP_NEAREST(0x2700).
gl_GL_NEVER(0x0200).
gl_GL_NICEST(0x1102).
gl_GL_NO_ERROR(0x0).
gl_GL_NONE(0x0).
gl_GL_NOOP(0x1505).
gl_GL_NOR(0x1508).
gl_GL_NORMAL_ARRAY(0x8075).
gl_GL_NORMAL_ARRAY_COUNT_EXT(0x8080).
gl_GL_NORMAL_ARRAY_EXT(0x8075).
gl_GL_NORMAL_ARRAY_POINTER(0x808F).
gl_GL_NORMAL_ARRAY_POINTER_EXT(0x808F).
gl_GL_NORMAL_ARRAY_STRIDE(0x807F).
gl_GL_NORMAL_ARRAY_STRIDE_EXT(0x807F).
gl_GL_NORMAL_ARRAY_TYPE(0x807E).
gl_GL_NORMAL_ARRAY_TYPE_EXT(0x807E).
gl_GL_NORMALIZE(0x0BA1).
gl_GL_NORMAL_MAP_NV(0x8511).
gl_GL_NOTEQUAL(0x0205).
gl_GL_NV_texgen_reflection(1).
gl_GL_OBJECT_LINEAR(0x2401).
gl_GL_OBJECT_PLANE(0x2501).
gl_GL_OCCLUSION_TEST_HP(0x8165).
gl_GL_OCCLUSION_TEST_RESULT_HP(0x8166).
gl_GL_ONE(0x1).
gl_GL_ONE_MINUS_CONSTANT_ALPHA(0x8004).
gl_GL_ONE_MINUS_CONSTANT_ALPHA_EXT(0x8004).
gl_GL_ONE_MINUS_CONSTANT_COLOR(0x8002).
gl_GL_ONE_MINUS_CONSTANT_COLOR_EXT(0x8002).
gl_GL_ONE_MINUS_DST_ALPHA(0x0305).
gl_GL_ONE_MINUS_DST_COLOR(0x0307).
gl_GL_ONE_MINUS_SRC_ALPHA(0x0303).
gl_GL_ONE_MINUS_SRC_COLOR(0x0301).
gl_GL_OR(0x1507).
gl_GL_ORDER(0x0A01).
gl_GL_OR_INVERTED(0x150D).
gl_GL_OR_REVERSE(0x150B).
gl_GL_OUT_OF_MEMORY(0x0505).
gl_GL_PACK_ALIGNMENT(0x0D05).
gl_GL_PACK_IMAGE_HEIGHT(0x806C).
gl_GL_PACK_IMAGE_HEIGHT_EXT(0x806C).
gl_GL_PACK_LSB_FIRST(0x0D01).
gl_GL_PACK_ROW_LENGTH(0x0D02).
gl_GL_PACK_SKIP_IMAGES(0x806B).
gl_GL_PACK_SKIP_IMAGES_EXT(0x806B).
gl_GL_PACK_SKIP_PIXELS(0x0D04).
gl_GL_PACK_SKIP_ROWS(0x0D03).
gl_GL_PACK_SWAP_BYTES(0x0D00).
gl_GL_PASS_THROUGH_TOKEN(0x0700).
gl_GL_PERSPECTIVE_CORRECTION_HINT(0x0C50).
gl_GL_PIXEL_MAP_A_TO_A(0x0C79).
gl_GL_PIXEL_MAP_A_TO_A_SIZE(0x0CB9).
gl_GL_PIXEL_MAP_B_TO_B(0x0C78).
gl_GL_PIXEL_MAP_B_TO_B_SIZE(0x0CB8).
gl_GL_PIXEL_MAP_G_TO_G(0x0C77).
gl_GL_PIXEL_MAP_G_TO_G_SIZE(0x0CB7).
gl_GL_PIXEL_MAP_I_TO_A(0x0C75).
gl_GL_PIXEL_MAP_I_TO_A_SIZE(0x0CB5).
gl_GL_PIXEL_MAP_I_TO_B(0x0C74).
gl_GL_PIXEL_MAP_I_TO_B_SIZE(0x0CB4).
gl_GL_PIXEL_MAP_I_TO_G(0x0C73).
gl_GL_PIXEL_MAP_I_TO_G_SIZE(0x0CB3).
gl_GL_PIXEL_MAP_I_TO_I(0x0C70).
gl_GL_PIXEL_MAP_I_TO_I_SIZE(0x0CB0).
gl_GL_PIXEL_MAP_I_TO_R(0x0C72).
gl_GL_PIXEL_MAP_I_TO_R_SIZE(0x0CB2).
gl_GL_PIXEL_MAP_R_TO_R(0x0C76).
gl_GL_PIXEL_MAP_R_TO_R_SIZE(0x0CB6).
gl_GL_PIXEL_MAP_S_TO_S(0x0C71).
gl_GL_PIXEL_MAP_S_TO_S_SIZE(0x0CB1).
gl_GL_PIXEL_MODE_BIT(0x00000020).
gl_GL_POINT(0x1B00).
gl_GL_POINT_BIT(0x00000002).
gl_GL_POINT_FADE_THRESHOLD_SIZE_EXT(0x8128).
gl_GL_POINTS(0x0000).
gl_GL_POINT_SIZE(0x0B11).
gl_GL_POINT_SIZE_GRANULARITY(0x0B13).
gl_GL_POINT_SIZE_MAX_EXT(0x8127).
gl_GL_POINT_SIZE_MIN_EXT(0x8126).
gl_GL_POINT_SIZE_RANGE(0x0B12).
gl_GL_POINT_SMOOTH(0x0B10).
gl_GL_POINT_SMOOTH_HINT(0x0C51).
gl_GL_POINT_TOKEN(0x0701).
gl_GL_POLYGON(0x0009).
gl_GL_POLYGON_BIT(0x00000008).
gl_GL_POLYGON_MODE(0x0B40).
gl_GL_POLYGON_OFFSET_BIAS_EXT(0x8039).
gl_GL_POLYGON_OFFSET_EXT(0x8037).
gl_GL_POLYGON_OFFSET_FACTOR(0x8038).
gl_GL_POLYGON_OFFSET_FACTOR_EXT(0x8038).
gl_GL_POLYGON_OFFSET_FILL(0x8037).
gl_GL_POLYGON_OFFSET_LINE(0x2A02).
gl_GL_POLYGON_OFFSET_POINT(0x2A01).
gl_GL_POLYGON_OFFSET_UNITS(0x2A00).
gl_GL_POLYGON_SMOOTH(0x0B41).
gl_GL_POLYGON_SMOOTH_HINT(0x0C53).
gl_GL_POLYGON_STIPPLE(0x0B42).
gl_GL_POLYGON_STIPPLE_BIT(0x00000010).
gl_GL_POLYGON_TOKEN(0x0703).
gl_GL_POSITION(0x1203).
gl_GL_POST_COLOR_MATRIX_ALPHA_BIAS(0x80BB).
gl_GL_POST_COLOR_MATRIX_ALPHA_SCALE(0x80B7).
gl_GL_POST_COLOR_MATRIX_BLUE_BIAS(0x80BA).
gl_GL_POST_COLOR_MATRIX_BLUE_SCALE(0x80B6).
gl_GL_POST_COLOR_MATRIX_COLOR_TABLE(0x80D2).
gl_GL_POST_COLOR_MATRIX_GREEN_BIAS(0x80B9).
gl_GL_POST_COLOR_MATRIX_GREEN_SCALE(0x80B5).
gl_GL_POST_COLOR_MATRIX_RED_BIAS(0x80B8).
gl_GL_POST_COLOR_MATRIX_RED_SCALE(0x80B4).
gl_GL_POST_CONVOLUTION_ALPHA_BIAS(0x8023).
gl_GL_POST_CONVOLUTION_ALPHA_SCALE(0x801F).
gl_GL_POST_CONVOLUTION_BLUE_BIAS(0x8022).
gl_GL_POST_CONVOLUTION_BLUE_SCALE(0x801E).
gl_GL_POST_CONVOLUTION_COLOR_TABLE(0x80D1).
gl_GL_POST_CONVOLUTION_GREEN_BIAS(0x8021).
gl_GL_POST_CONVOLUTION_GREEN_SCALE(0x801D).
gl_GL_POST_CONVOLUTION_RED_BIAS(0x8020).
gl_GL_POST_CONVOLUTION_RED_SCALE(0x801C).
gl_GL_PROJECTION(0x1701).
gl_GL_PROJECTION_MATRIX(0x0BA7).
gl_GL_PROJECTION_STACK_DEPTH(0x0BA4).
gl_GL_PROXY_COLOR_TABLE(0x80D3).
gl_GL_PROXY_HISTOGRAM(0x8025).
gl_GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE(0x80D5).
gl_GL_PROXY_POST_CONVOLUTION_COLOR_TABLE(0x80D4).
gl_GL_PROXY_TEXTURE_1D(0x8063).
gl_GL_PROXY_TEXTURE_2D(0x8064).
gl_GL_PROXY_TEXTURE_3D(0x8070).
gl_GL_PROXY_TEXTURE_3D_EXT(0x8070).
gl_GL_Q(0x2003).
gl_GL_QUADRATIC_ATTENUATION(0x1209).
gl_GL_QUADS(0x0007).
gl_GL_QUAD_STRIP(0x0008).
gl_GL_R(0x2002).
gl_GL_R3_G3_B2(0x2A10).
gl_GL_READ_BUFFER(0x0C02).
gl_GL_RED(0x1903).
gl_GL_RED_BIAS(0x0D15).
gl_GL_RED_BITS(0x0D52).
gl_GL_RED_SCALE(0x0D14).
gl_GL_REDUCE(0x8016).
gl_GL_REFLECTION_MAP_NV(0x8512).
gl_GL_RENDER(0x1C00).
gl_GL_RENDERER(0x1F01).
gl_GL_RENDER_MODE(0x0C40).
gl_GL_REPEAT(0x2901).
gl_GL_REPLACE(0x1E01).
gl_GL_REPLICATE_BORDER(0x8153).
gl_GL_RESCALE_NORMAL(0x803A).
gl_GL_RESCALE_NORMAL_EXT(0x803A).
gl_GL_RETURN(0x0102).
gl_GL_RGB(0x1907).
gl_GL_RGB10(0x8052).
gl_GL_RGB10_A2(0x8059).
gl_GL_RGB12(0x8053).
gl_GL_RGB16(0x8054).
gl_GL_RGB4(0x804F).
gl_GL_RGB5(0x8050).
gl_GL_RGB5_A1(0x8057).
gl_GL_RGB8(0x8051).
gl_GL_RGBA(0x1908).
gl_GL_RGBA12(0x805A).
gl_GL_RGBA16(0x805B).
gl_GL_RGBA2(0x8055).
gl_GL_RGBA4(0x8056).
gl_GL_RGBA8(0x8058).
gl_GL_RGBA_MODE(0x0C31).
gl_GL_RIGHT(0x0407).
gl_GL_S(0x2000).
gl_GL_SCISSOR_BIT(0x00080000).
gl_GL_SCISSOR_BOX(0x0C10).
gl_GL_SCISSOR_TEST(0x0C11).
gl_GL_SELECT(0x1C02).
gl_GL_SELECTION_BUFFER_POINTER(0x0DF3).
gl_GL_SELECTION_BUFFER_SIZE(0x0DF4).
gl_GL_SEPARABLE_2D(0x8012).
gl_GL_SEPARATE_SPECULAR_COLOR(0x81FA).
gl_GL_SET(0x150F).
gl_GL_SGIS_texture_edge_clamp(1).
gl_GL_SHADE_MODEL(0x0B54).
gl_GL_SHARED_TEXTURE_PALETTE_EXT(0x81FB).
gl_GL_SHININESS(0x1601).
gl_GL_SHORT(0x1402).
gl_GL_SINgl_GLE_COLOR(0x81F9).
gl_GL_SMOOTH(0x1D01).
gl_GL_SMOOTH_LINE_WIDTH_GRANULARITY(0x0B23).
gl_GL_SMOOTH_LINE_WIDTH_RANGE(0x0B22).
gl_GL_SMOOTH_POINT_SIZE_GRANULARITY(0x0B13).
gl_GL_SMOOTH_POINT_SIZE_RANGE(0x0B12).
gl_GL_SPECULAR(0x1202).
gl_GL_SPHERE_MAP(0x2402).
gl_GL_SPOT_CUTOFF(0x1206).
gl_GL_SPOT_DIRECTION(0x1204).
gl_GL_SPOT_EXPONENT(0x1205).
gl_GL_SRC_ALPHA(0x0302).
gl_GL_SRC_ALPHA_SATURATE(0x0308).
gl_GL_SRC_COLOR(0x0300).
gl_GL_STACK_OVERFLOW(0x0503).
gl_GL_STACK_UNDERFLOW(0x0504).
gl_GL_STENCIL(0x1802).
gl_GL_STENCIL_BITS(0x0D57).
gl_GL_STENCIL_BUFFER_BIT(0x00000400).
gl_GL_STENCIL_CLEAR_VALUE(0x0B91).
gl_GL_STENCIL_FAIL(0x0B94).
gl_GL_STENCIL_FUNC(0x0B92).
gl_GL_STENCIL_INDEX(0x1901).
gl_GL_STENCIL_PASS_DEPTH_FAIL(0x0B95).
gl_GL_STENCIL_PASS_DEPTH_PASS(0x0B96).
gl_GL_STENCIL_REF(0x0B97).
gl_GL_STENCIL_TEST(0x0B90).
gl_GL_STENCIL_VALUE_MASK(0x0B93).
gl_GL_STENCIL_WRITEMASK(0x0B98).
gl_GL_STEREO(0x0C33).
gl_GL_SUBPIXEL_BITS(0x0D50).
gl_GL_T(0x2001).
gl_GL_T2F_C3F_V3F(0x2A2A).
gl_GL_T2F_C4F_N3F_V3F(0x2A2C).
gl_GL_T2F_C4UB_V3F(0x2A29).
gl_GL_T2F_N3F_V3F(0x2A2B).
gl_GL_T2F_V3F(0x2A27).
gl_GL_T4F_C4F_N3F_V4F(0x2A2D).
gl_GL_T4F_V4F(0x2A28).
gl_GL_TABLE_TOO_LARGE(0x8031).
gl_GL_TABLE_TOO_LARGE_EXT(0x8031).
gl_GL_TEXTURE0_ARB(0x84C0).
gl_GL_TEXTURE(0x1702).
gl_GL_TEXTURE10_ARB(0x84CA).
gl_GL_TEXTURE11_ARB(0x84CB).
gl_GL_TEXTURE12_ARB(0x84CC).
gl_GL_TEXTURE13_ARB(0x84CD).
gl_GL_TEXTURE14_ARB(0x84CE).
gl_GL_TEXTURE15_ARB(0x84CF).
gl_GL_TEXTURE16_ARB(0x84D0).
gl_GL_TEXTURE17_ARB(0x84D1).
gl_GL_TEXTURE18_ARB(0x84D2).
gl_GL_TEXTURE19_ARB(0x84D3).
gl_GL_TEXTURE1_ARB(0x84C1).
gl_GL_TEXTURE_1D(0x0DE0).
gl_GL_TEXTURE_1D_BINDING_EXT(0x8068).
gl_GL_TEXTURE20_ARB(0x84D4).
gl_GL_TEXTURE21_ARB(0x84D5).
gl_GL_TEXTURE22_ARB(0x84D6).
gl_GL_TEXTURE23_ARB(0x84D7).
gl_GL_TEXTURE24_ARB(0x84D8).
gl_GL_TEXTURE25_ARB(0x84D9).
gl_GL_TEXTURE26_ARB(0x84DA).
gl_GL_TEXTURE27_ARB(0x84DB).
gl_GL_TEXTURE28_ARB(0x84DC).
gl_GL_TEXTURE29_ARB(0x84DD).
gl_GL_TEXTURE2_ARB(0x84C2).
gl_GL_TEXTURE_2D(0x0DE1).
gl_GL_TEXTURE_2D_BINDING_EXT(0x8069).
gl_GL_TEXTURE30_ARB(0x84DE).
gl_GL_TEXTURE31_ARB(0x84DF).
gl_GL_TEXTURE3_ARB(0x84C3).
gl_GL_TEXTURE_3D(0x806F).
gl_GL_TEXTURE_3D_BINDING_EXT(0x806A).
gl_GL_TEXTURE_3D_EXT(0x806F).
gl_GL_TEXTURE4_ARB(0x84C4).
gl_GL_TEXTURE5_ARB(0x84C5).
gl_GL_TEXTURE6_ARB(0x84C6).
gl_GL_TEXTURE7_ARB(0x84C7).
gl_GL_TEXTURE8_ARB(0x84C8).
gl_GL_TEXTURE9_ARB(0x84C9).
gl_GL_TEXTURE_ALPHA_SIZE(0x805F).
gl_GL_TEXTURE_BASE_LEVEL(0x813C).
gl_GL_TEXTURE_BINDING_1D(0x8068).
gl_GL_TEXTURE_BINDING_2D(0x8069).
gl_GL_TEXTURE_BINDING_3D(0x806A).
gl_GL_TEXTURE_BIT(0x00040000).
gl_GL_TEXTURE_BLUE_SIZE(0x805E).
gl_GL_TEXTURE_BORDER(0x1005).
gl_GL_TEXTURE_BORDER_COLOR(0x1004).
gl_GL_TEXTURE_COMPONENTS(0x1003).
gl_GL_TEXTURE_COORD_ARRAY(0x8078).
gl_GL_TEXTURE_COORD_ARRAY_COUNT_EXT(0x808B).
gl_GL_TEXTURE_COORD_ARRAY_EXT(0x8078).
gl_GL_TEXTURE_COORD_ARRAY_POINTER(0x8092).
gl_GL_TEXTURE_COORD_ARRAY_POINTER_EXT(0x8092).
gl_GL_TEXTURE_COORD_ARRAY_SIZE(0x8088).
gl_GL_TEXTURE_COORD_ARRAY_SIZE_EXT(0x8088).
gl_GL_TEXTURE_COORD_ARRAY_STRIDE(0x808A).
gl_GL_TEXTURE_COORD_ARRAY_STRIDE_EXT(0x808A).
gl_GL_TEXTURE_COORD_ARRAY_TYPE(0x8089).
gl_GL_TEXTURE_COORD_ARRAY_TYPE_EXT(0x8089).
gl_GL_TEXTURE_DEPTH(0x8071).
gl_GL_TEXTURE_DEPTH_EXT(0x8071).
gl_GL_TEXTURE_ENV(0x2300).
gl_GL_TEXTURE_ENV_COLOR(0x2201).
gl_GL_TEXTURE_ENV_MODE(0x2200).
gl_GL_TEXTURE_GEN_MODE(0x2500).
gl_GL_TEXTURE_GEN_Q(0x0C63).
gl_GL_TEXTURE_GEN_R(0x0C62).
gl_GL_TEXTURE_GEN_S(0x0C60).
gl_GL_TEXTURE_GEN_T(0x0C61).
gl_GL_TEXTURE_GREEN_SIZE(0x805D).
gl_GL_TEXTURE_HEIGHT(0x1001).
gl_GL_TEXTURE_INDEX_SIZE_EXT(0x80ED).
gl_GL_TEXTURE_INTENSITY_SIZE(0x8061).
gl_GL_TEXTURE_INTERNAL_FORMAT(0x1003).
gl_GL_TEXTURE_LUMINANCE_SIZE(0x8060).
gl_GL_TEXTURE_MAG_FILTER(0x2800).
gl_GL_TEXTURE_MATRIX(0x0BA8).
gl_GL_TEXTURE_MAX_LEVEL(0x813D).
gl_GL_TEXTURE_MAX_LOD(0x813B).
gl_GL_TEXTURE_MIN_FILTER(0x2801).
gl_GL_TEXTURE_MIN_LOD(0x813A).
gl_GL_TEXTURE_PRIORITY(0x8066).
gl_GL_TEXTURE_PRIORITY_EXT(0x8066).
gl_GL_TEXTURE_RED_SIZE(0x805C).
gl_GL_TEXTURE_RESIDENT(0x8067).
gl_GL_TEXTURE_RESIDENT_EXT(0x8067).
gl_GL_TEXTURE_STACK_DEPTH(0x0BA5).
gl_GL_TEXTURE_WIDTH(0x1000).
gl_GL_TEXTURE_WRAP_R(0x8072).
gl_GL_TEXTURE_WRAP_R_EXT(0x8072).
gl_GL_TEXTURE_WRAP_S(0x2802).
gl_GL_TEXTURE_WRAP_T(0x2803).
gl_GL_TRANSFORM_BIT(0x00001000).
gl_GL_TRIANGLE_FAN(0x0006).
gl_GL_TRIANGLES(0x0004).
gl_GL_TRIANGLE_STRIP(0x0005).
gl_GL_TRUE(0x1).
gl_GL_UNPACK_ALIGNMENT(0x0CF5).
gl_GL_UNPACK_IMAGE_HEIGHT(0x806E).
gl_GL_UNPACK_IMAGE_HEIGHT_EXT(0x806E).
gl_GL_UNPACK_LSB_FIRST(0x0CF1).
gl_GL_UNPACK_ROW_LENGTH(0x0CF2).
gl_GL_UNPACK_SKIP_IMAGES(0x806D).
gl_GL_UNPACK_SKIP_IMAGES_EXT(0x806D).
gl_GL_UNPACK_SKIP_PIXELS(0x0CF4).
gl_GL_UNPACK_SKIP_ROWS(0x0CF3).
gl_GL_UNPACK_SWAP_BYTES(0x0CF0).
gl_GL_UNSIGNED_BYTE(0x1401).
gl_GL_UNSIGNED_BYTE_2_3_3_REV(0x8362).
gl_GL_UNSIGNED_BYTE_3_3_2(0x8032).
gl_GL_UNSIGNED_INT(0x1405).
gl_GL_UNSIGNED_INT_10_10_10_2(0x8036).
gl_GL_UNSIGNED_INT_2_10_10_10_REV(0x8368).
gl_GL_UNSIGNED_INT_8_8_8_8(0x8035).
gl_GL_UNSIGNED_INT_8_8_8_8_REV(0x8367).
gl_GL_UNSIGNED_SHORT(0x1403).
gl_GL_UNSIGNED_SHORT_1_5_5_5_REV(0x8366).
gl_GL_UNSIGNED_SHORT_4_4_4_4(0x8033).
gl_GL_UNSIGNED_SHORT_4_4_4_4_REV(0x8365).
gl_GL_UNSIGNED_SHORT_5_5_5_1(0x8034).
gl_GL_UNSIGNED_SHORT_5_6_5(0x8363).
gl_GL_UNSIGNED_SHORT_5_6_5_REV(0x8364).
gl_GL_V2F(0x2A20).
gl_GL_V3F(0x2A21).
gl_GL_VENDOR(0x1F00).
gl_GL_VERSION(0x1F02).
gl_GL_VERTEX_ARRAY(0x8074).
gl_GL_VERTEX_ARRAY_COUNT_EXT(0x807D).
gl_GL_VERTEX_ARRAY_EXT(0x8074).
gl_GL_VERTEX_ARRAY_POINTER(0x808E).
gl_GL_VERTEX_ARRAY_POINTER_EXT(0x808E).
gl_GL_VERTEX_ARRAY_SIZE(0x807A).
gl_GL_VERTEX_ARRAY_SIZE_EXT(0x807A).
gl_GL_VERTEX_ARRAY_STRIDE(0x807C).
gl_GL_VERTEX_ARRAY_STRIDE_EXT(0x807C).
gl_GL_VERTEX_ARRAY_TYPE(0x807B).
gl_GL_VERTEX_ARRAY_TYPE_EXT(0x807B).
gl_GL_VIEWPORT(0x0BA2).
gl_GL_VIEWPORT_BIT(0x00000800).
gl_GL_XOR(0x1506).
gl_GL_ZERO(0x0).
gl_GL_ZOOM_X(0x0D16).
gl_GL_ZOOM_Y(0x0D17).

gl_opts(Expr,Val) :- arithmetic_expression_value(Expr,Val).
