:- module(glut_defs,[glut_opts/2]).

% Definitions, Bindings and Keys from glut.h

:-arithmetic_function(glut_GLUT_ACCUM/0).
:-arithmetic_function(glut_GLUT_ACTIVE_ALT/0).
:-arithmetic_function(glut_GLUT_ACTIVE_CTRL/0).
:-arithmetic_function(glut_GLUT_ACTIVE_SHIFT/0).
:-arithmetic_function(glut_GLUT_ALPHA/0).
:-arithmetic_function(glut_GLUT_API_VERSION/0).
:-arithmetic_function(glut_GLUT_BLUE/0).
:-arithmetic_function(glut_GLUT_CURSOR_BOTTOM_LEFT_CORNER/0).
:-arithmetic_function(glut_GLUT_CURSOR_BOTTOM_RIGHT_CORNER/0).
:-arithmetic_function(glut_GLUT_CURSOR_BOTTOM_SIDE/0).
:-arithmetic_function(glut_GLUT_CURSOR_CROSSHAIR/0).
:-arithmetic_function(glut_GLUT_CURSOR_CYCLE/0).
:-arithmetic_function(glut_GLUT_CURSOR_DESTROY/0).
:-arithmetic_function(glut_GLUT_CURSOR_FULL_CROSSHAIR/0).
:-arithmetic_function(glut_GLUT_CURSOR_HELP/0).
:-arithmetic_function(glut_GLUT_CURSOR_INFO/0).
:-arithmetic_function(glut_GLUT_CURSOR_INHERIT/0).
:-arithmetic_function(glut_GLUT_CURSOR_LEFT_ARROW/0).
:-arithmetic_function(glut_GLUT_CURSOR_LEFT_RIGHT/0).
:-arithmetic_function(glut_GLUT_CURSOR_LEFT_SIDE/0).
:-arithmetic_function(glut_GLUT_CURSOR_NONE/0).
:-arithmetic_function(glut_GLUT_CURSOR_RIGHT_ARROW/0).
:-arithmetic_function(glut_GLUT_CURSOR_RIGHT_SIDE/0).
:-arithmetic_function(glut_GLUT_CURSOR_SPRAY/0).
:-arithmetic_function(glut_GLUT_CURSOR_TEXT/0).
:-arithmetic_function(glut_GLUT_CURSOR_TOP_LEFT_CORNER/0).
:-arithmetic_function(glut_GLUT_CURSOR_TOP_RIGHT_CORNER/0).
:-arithmetic_function(glut_GLUT_CURSOR_TOP_SIDE/0).
:-arithmetic_function(glut_GLUT_CURSOR_UP_DOWN/0).
:-arithmetic_function(glut_GLUT_CURSOR_WAIT/0).
:-arithmetic_function(glut_GLUT_DEPTH/0).
:-arithmetic_function(glut_GLUT_DEVICE_IGNORE_KEY_REPEAT/0).
:-arithmetic_function(glut_GLUT_DEVICE_KEY_REPEAT/0).
:-arithmetic_function(glut_GLUT_DISPLAY_MODE_POSSIBLE/0).
:-arithmetic_function(glut_GLUT_DOUBLE/0).
:-arithmetic_function(glut_GLUT_DOWN/0).
:-arithmetic_function(glut_GLUT_ELAPSED_TIME/0).
:-arithmetic_function(glut_GLUT_ENTERED/0).
:-arithmetic_function(glut_GLUT_FULLY_COVERED/0).
:-arithmetic_function(glut_GLUT_FULLY_RETAINED/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_ACTIVE/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_DISPLAY_CHANGED/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_HEIGHT/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_PIXEL_DEPTH/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_POSSIBLE/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_REFRESH_RATE/0).
:-arithmetic_function(glut_GLUT_GAME_MODE_WIDTH/0).
:-arithmetic_function(glut_GLUT_GREEN/0).
:-arithmetic_function(glut_GLUT_HAS_DIAL_AND_BUTTON_BOX/0).
:-arithmetic_function(glut_GLUT_HAS_JOYSTICK/0).
:-arithmetic_function(glut_GLUT_HAS_KEYBOARD/0).
:-arithmetic_function(glut_GLUT_HAS_MOUSE/0).
:-arithmetic_function(glut_GLUT_HAS_OVERLAY/0).
:-arithmetic_function(glut_GLUT_HAS_SPACEBALL/0).
:-arithmetic_function(glut_GLUT_HAS_TABLET/0).
:-arithmetic_function(glut_GLUT_HIDDEN/0).
:-arithmetic_function(glut_GLUT_INDEX/0).
:-arithmetic_function(glut_GLUT_INIT_DISPLAY_MODE/0).
:-arithmetic_function(glut_GLUT_INIT_WINDOW_HEIGHT/0).
:-arithmetic_function(glut_GLUT_INIT_WINDOW_WIDTH/0).
:-arithmetic_function(glut_GLUT_INIT_WINDOW_X/0).
:-arithmetic_function(glut_GLUT_INIT_WINDOW_Y/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_AXES/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_BUTTON_A/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_BUTTON_B/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_BUTTON_C/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_BUTTON_D/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_BUTTONS/0).
:-arithmetic_function(glut_GLUT_JOYSTICK_POLL_RATE/0).
:-arithmetic_function(glut_GLUT_KEY_DOWN/0).
:-arithmetic_function(glut_GLUT_KEY_END/0).
:-arithmetic_function(glut_GLUT_KEY_F1/0).
:-arithmetic_function(glut_GLUT_KEY_F10/0).
:-arithmetic_function(glut_GLUT_KEY_F11/0).
:-arithmetic_function(glut_GLUT_KEY_F12/0).
:-arithmetic_function(glut_GLUT_KEY_F2/0).
:-arithmetic_function(glut_GLUT_KEY_F3/0).
:-arithmetic_function(glut_GLUT_KEY_F4/0).
:-arithmetic_function(glut_GLUT_KEY_F5/0).
:-arithmetic_function(glut_GLUT_KEY_F6/0).
:-arithmetic_function(glut_GLUT_KEY_F7/0).
:-arithmetic_function(glut_GLUT_KEY_F8/0).
:-arithmetic_function(glut_GLUT_KEY_F9/0).
:-arithmetic_function(glut_GLUT_KEY_HOME/0).
:-arithmetic_function(glut_GLUT_KEY_INSERT/0).
:-arithmetic_function(glut_GLUT_KEY_LEFT/0).
:-arithmetic_function(glut_GLUT_KEY_PAGE_DOWN/0).
:-arithmetic_function(glut_GLUT_KEY_PAGE_UP/0).
:-arithmetic_function(glut_GLUT_KEY_REPEAT_DEFAULT/0).
:-arithmetic_function(glut_GLUT_KEY_REPEAT_OFF/0).
:-arithmetic_function(glut_GLUT_KEY_REPEAT_ON/0).
:-arithmetic_function(glut_GLUT_KEY_RIGHT/0).
:-arithmetic_function(glut_GLUT_KEY_UP/0).
:-arithmetic_function(glut_GLUT_LAYER_IN_USE/0).
:-arithmetic_function(glut_GLUT_LEFT/0).
:-arithmetic_function(glut_GLUT_LEFT_BUTTON/0).
:-arithmetic_function(glut_GLUT_LUMINANCE/0).
:-arithmetic_function(glut_GLUT_MENU_IN_USE/0).
:-arithmetic_function(glut_GLUT_MENU_NOT_IN_USE/0).
:-arithmetic_function(glut_GLUT_MENU_NUM_ITEMS/0).
:-arithmetic_function(glut_GLUT_MIDDLE_BUTTON/0).
:-arithmetic_function(glut_GLUT_MULTISAMPLE/0).
:-arithmetic_function(glut_GLUT_NORMAL/0).
:-arithmetic_function(glut_GLUT_NORMAL/0).
:-arithmetic_function(glut_GLUT_NORMAL_DAMAGED/0).
:-arithmetic_function(glut_GLUT_NOT_VISIBLE/0).
:-arithmetic_function(glut_GLUT_NUM_BUTTON_BOX_BUTTONS/0).
:-arithmetic_function(glut_GLUT_NUM_DIALS/0).
:-arithmetic_function(glut_GLUT_NUM_MOUSE_BUTTONS/0).
:-arithmetic_function(glut_GLUT_NUM_SPACEBALL_BUTTONS/0).
:-arithmetic_function(glut_GLUT_NUM_TABLET_BUTTONS/0).
:-arithmetic_function(glut_GLUT_OVERLAY/0).
:-arithmetic_function(glut_GLUT_OVERLAY/0).
:-arithmetic_function(glut_GLUT_OVERLAY_DAMAGED/0).
:-arithmetic_function(glut_GLUT_OVERLAY_POSSIBLE/0).
:-arithmetic_function(glut_GLUT_OWNS_JOYSTICK/0).
:-arithmetic_function(glut_GLUT_PARTIALLY_RETAINED/0).
:-arithmetic_function(glut_GLUT_RED/0).
:-arithmetic_function(glut_GLUT_RGB/0).
:-arithmetic_function(glut_GLUT_RGBA/0).
:-arithmetic_function(glut_GLUT_RIGHT_BUTTON/0).
:-arithmetic_function(glut_GLUT_SCREEN_HEIGHT/0).
:-arithmetic_function(glut_GLUT_SCREEN_HEIGHT_MM/0).
:-arithmetic_function(glut_GLUT_SCREEN_WIDTH/0).
:-arithmetic_function(glut_GLUT_SCREEN_WIDTH_MM/0).
:-arithmetic_function(glut_GLUT_SINGLE/0).
:-arithmetic_function(glut_GLUT_STENCIL/0).
:-arithmetic_function(glut_GLUT_STEREO/0).
:-arithmetic_function(glut_GLUT_TRANSPARENT_INDEX/0).
:-arithmetic_function(glut_GLUT_UP/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_HEIGHT/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_HEIGHT_DELTA/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_IN_USE/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_POSSIBLE/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_WIDTH/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_WIDTH_DELTA/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_X/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_X_DELTA/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_Y/0).
:-arithmetic_function(glut_GLUT_VIDEO_RESIZE_Y_DELTA/0).
:-arithmetic_function(glut_GLUT_VISIBLE/0).
:-arithmetic_function(glut_GLUT_WINDOW_ACCUM_ALPHA_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_ACCUM_BLUE_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_ACCUM_GREEN_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_ACCUM_RED_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_ALPHA_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_BLUE_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_BUFFER_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_COLORMAP_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_CURSOR/0).
:-arithmetic_function(glut_GLUT_WINDOW_DEPTH_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_DOUBLEBUFFER/0).
:-arithmetic_function(glut_GLUT_WINDOW_FORMAT_ID/0).
:-arithmetic_function(glut_GLUT_WINDOW_GREEN_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_HEIGHT/0).
:-arithmetic_function(glut_GLUT_WINDOW_NUM_CHILDREN/0).
:-arithmetic_function(glut_GLUT_WINDOW_NUM_SAMPLES/0).
:-arithmetic_function(glut_GLUT_WINDOW_PARENT/0).
:-arithmetic_function(glut_GLUT_WINDOW_RED_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_RGBA/0).
:-arithmetic_function(glut_GLUT_WINDOW_STENCIL_SIZE/0).
:-arithmetic_function(glut_GLUT_WINDOW_STEREO/0).
:-arithmetic_function(glut_GLUT_WINDOW_WIDTH/0).
:-arithmetic_function(glut_GLUT_WINDOW_X/0).
:-arithmetic_function(glut_GLUT_WINDOW_Y/0).
:-arithmetic_function(glut_GLUT_XLIB_IMPLEMENTATION/0).
glut_GLUT_ACCUM(4).
glut_GLUT_ACTIVE_ALT(4).
glut_GLUT_ACTIVE_CTRL(2).
glut_GLUT_ACTIVE_SHIFT(1).
glut_GLUT_ALPHA(8).
glut_GLUT_API_VERSION(3).
glut_GLUT_BLUE(2).
glut_GLUT_CURSOR_BOTTOM_LEFT_CORNER(19).
glut_GLUT_CURSOR_BOTTOM_RIGHT_CORNER(18).
glut_GLUT_CURSOR_BOTTOM_SIDE(13).
glut_GLUT_CURSOR_CROSSHAIR(9).
glut_GLUT_CURSOR_CYCLE(5).
glut_GLUT_CURSOR_DESTROY(3).
glut_GLUT_CURSOR_FULL_CROSSHAIR(102).
glut_GLUT_CURSOR_HELP(4).
glut_GLUT_CURSOR_INFO(2).
glut_GLUT_CURSOR_INHERIT(100).
glut_GLUT_CURSOR_LEFT_ARROW(1).
glut_GLUT_CURSOR_LEFT_RIGHT(11).
glut_GLUT_CURSOR_LEFT_SIDE(14).
glut_GLUT_CURSOR_NONE(101).
glut_GLUT_CURSOR_RIGHT_ARROW(0).
glut_GLUT_CURSOR_RIGHT_SIDE(15).
glut_GLUT_CURSOR_SPRAY(6).
glut_GLUT_CURSOR_TEXT(8).
glut_GLUT_CURSOR_TOP_LEFT_CORNER(16).
glut_GLUT_CURSOR_TOP_RIGHT_CORNER(17).
glut_GLUT_CURSOR_TOP_SIDE(12).
glut_GLUT_CURSOR_UP_DOWN(10).
glut_GLUT_CURSOR_WAIT(7).
glut_GLUT_DEPTH(16).
glut_GLUT_DEVICE_IGNORE_KEY_REPEAT(610).
glut_GLUT_DEVICE_KEY_REPEAT(611).
glut_GLUT_DISPLAY_MODE_POSSIBLE(400).
glut_GLUT_DOUBLE(2).
glut_GLUT_DOWN(0).
glut_GLUT_ELAPSED_TIME(700).
glut_GLUT_ENTERED(1).
glut_GLUT_FULLY_COVERED(3).
glut_GLUT_FULLY_RETAINED(1).
glut_GLUT_GAME_MODE_ACTIVE(0).
glut_GLUT_GAME_MODE_DISPLAY_CHANGED(6).
glut_GLUT_GAME_MODE_HEIGHT(3).
glut_GLUT_GAME_MODE_PIXEL_DEPTH(4).
glut_GLUT_GAME_MODE_POSSIBLE(1).
glut_GLUT_GAME_MODE_REFRESH_RATE(5).
glut_GLUT_GAME_MODE_WIDTH(2).
glut_GLUT_GREEN(1).
glut_GLUT_HAS_DIAL_AND_BUTTON_BOX(603).
glut_GLUT_HAS_JOYSTICK(612).
glut_GLUT_HAS_KEYBOARD(600).
glut_GLUT_HAS_MOUSE(601).
glut_GLUT_HAS_OVERLAY(802).
glut_GLUT_HAS_SPACEBALL(602).
glut_GLUT_HAS_TABLET(604).
glut_GLUT_HIDDEN(0).
glut_GLUT_INDEX(1).
glut_GLUT_INIT_DISPLAY_MODE(504).
glut_GLUT_INIT_WINDOW_HEIGHT(503).
glut_GLUT_INIT_WINDOW_WIDTH(502).
glut_GLUT_INIT_WINDOW_X(500).
glut_GLUT_INIT_WINDOW_Y(501).
glut_GLUT_JOYSTICK_AXES(615).
glut_GLUT_JOYSTICK_BUTTON_A(1).
glut_GLUT_JOYSTICK_BUTTON_B(2).
glut_GLUT_JOYSTICK_BUTTON_C(4).
glut_GLUT_JOYSTICK_BUTTON_D(8).
glut_GLUT_JOYSTICK_BUTTONS(614).
glut_GLUT_JOYSTICK_POLL_RATE(616).
glut_GLUT_KEY_DOWN(103).
glut_GLUT_KEY_END(107).
glut_GLUT_KEY_F10(10).
glut_GLUT_KEY_F1(1).
glut_GLUT_KEY_F11(11).
glut_GLUT_KEY_F12(12).
glut_GLUT_KEY_F2(2).
glut_GLUT_KEY_F3(3).
glut_GLUT_KEY_F4(4).
glut_GLUT_KEY_F5(5).
glut_GLUT_KEY_F6(6).
glut_GLUT_KEY_F7(7).
glut_GLUT_KEY_F8(8).
glut_GLUT_KEY_F9(9).
glut_GLUT_KEY_HOME(106).
glut_GLUT_KEY_INSERT(108).
glut_GLUT_KEY_LEFT(100).
glut_GLUT_KEY_PAGE_DOWN(105).
glut_GLUT_KEY_PAGE_UP(104).
glut_GLUT_KEY_REPEAT_DEFAULT(2).
glut_GLUT_KEY_REPEAT_OFF(0).
glut_GLUT_KEY_REPEAT_ON(1).
glut_GLUT_KEY_RIGHT(102).
glut_GLUT_KEY_UP(101).
glut_GLUT_LAYER_IN_USE(801).
glut_GLUT_LEFT(0).
glut_GLUT_LEFT_BUTTON(0).
glut_GLUT_LUMINANCE(512).
glut_GLUT_MENU_IN_USE(1).
glut_GLUT_MENU_NOT_IN_USE(0).
glut_GLUT_MENU_NUM_ITEMS(300).
glut_GLUT_MIDDLE_BUTTON(1).
glut_GLUT_MULTISAMPLE(128).
glut_GLUT_NORMAL(0).
glut_GLUT_NORMAL(0).
glut_GLUT_NORMAL_DAMAGED(804).
glut_GLUT_NOT_VISIBLE(0).
glut_GLUT_NUM_BUTTON_BOX_BUTTONS(607).
glut_GLUT_NUM_DIALS(608).
glut_GLUT_NUM_MOUSE_BUTTONS(605).
glut_GLUT_NUM_SPACEBALL_BUTTONS(606).
glut_GLUT_NUM_TABLET_BUTTONS(609).
glut_GLUT_OVERLAY(1).
glut_GLUT_OVERLAY(1).
glut_GLUT_OVERLAY_DAMAGED(805).
glut_GLUT_OVERLAY_POSSIBLE(800).
glut_GLUT_OWNS_JOYSTICK(613).
glut_GLUT_PARTIALLY_RETAINED(2).
glut_GLUT_RED(0).
glut_GLUT_RGB(0).
glut_GLUT_RGBA(0).
glut_GLUT_RIGHT_BUTTON(2).
glut_GLUT_SCREEN_HEIGHT(201).
glut_GLUT_SCREEN_HEIGHT_MM(203).
glut_GLUT_SCREEN_WIDTH(200).
glut_GLUT_SCREEN_WIDTH_MM(202).
glut_GLUT_SINGLE(0).
glut_GLUT_STENCIL(32).
glut_GLUT_STEREO(256).
glut_GLUT_TRANSPARENT_INDEX(803).
glut_GLUT_UP(1).
glut_GLUT_VIDEO_RESIZE_HEIGHT(909).
glut_GLUT_VIDEO_RESIZE_HEIGHT_DELTA(905).
glut_GLUT_VIDEO_RESIZE_IN_USE(901).
glut_GLUT_VIDEO_RESIZE_POSSIBLE(900).
glut_GLUT_VIDEO_RESIZE_WIDTH(908).
glut_GLUT_VIDEO_RESIZE_WIDTH_DELTA(904).
glut_GLUT_VIDEO_RESIZE_X(906).
glut_GLUT_VIDEO_RESIZE_X_DELTA(902).
glut_GLUT_VIDEO_RESIZE_Y(907).
glut_GLUT_VIDEO_RESIZE_Y_DELTA(903).
glut_GLUT_VISIBLE(1).
glut_GLUT_WINDOW_ACCUM_ALPHA_SIZE(114).
glut_GLUT_WINDOW_ACCUM_BLUE_SIZE(113).
glut_GLUT_WINDOW_ACCUM_GREEN_SIZE(112).
glut_GLUT_WINDOW_ACCUM_RED_SIZE(111).
glut_GLUT_WINDOW_ALPHA_SIZE(110).
glut_GLUT_WINDOW_BLUE_SIZE(109).
glut_GLUT_WINDOW_BUFFER_SIZE(104).
glut_GLUT_WINDOW_COLORMAP_SIZE(119).
glut_GLUT_WINDOW_CURSOR(122).
glut_GLUT_WINDOW_DEPTH_SIZE(106).
glut_GLUT_WINDOW_DOUBLEBUFFER(115).
glut_GLUT_WINDOW_FORMAT_ID(123).
glut_GLUT_WINDOW_GREEN_SIZE(108).
glut_GLUT_WINDOW_HEIGHT(103).
glut_GLUT_WINDOW_NUM_CHILDREN(118).
glut_GLUT_WINDOW_NUM_SAMPLES(120).
glut_GLUT_WINDOW_PARENT(117).
glut_GLUT_WINDOW_RED_SIZE(107).
glut_GLUT_WINDOW_RGBA(116).
glut_GLUT_WINDOW_STENCIL_SIZE(105).
glut_GLUT_WINDOW_STEREO(121).
glut_GLUT_WINDOW_WIDTH(102).
glut_GLUT_WINDOW_X(100).
glut_GLUT_WINDOW_Y(101).
glut_GLUT_XLIB_IMPLEMENTATION(15).

glut_opts(Expr,Val) :- arithmetic_expression_value(Expr,Val).
